"""Offline Chromium interaction and layout checks; no live endpoints are contacted.
Run after node tools/build-servicing-lab.mjs. Requires Python Playwright and Chromium.
"""
from pathlib import Path
import json, os
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'evidence'; OUT.mkdir(exist_ok=True)
HTML=(ROOT/'site/product-worlds/servicing-standalone.html').read_text()
results=[]
def check(name, condition):
    results.append({'name':name,'passed':bool(condition)})
    if not condition: raise AssertionError(name)
with sync_playwright() as p:
    options={'headless':True}
    if os.environ.get('CHROMIUM_PATH'): options['executable_path']=os.environ['CHROMIUM_PATH']
    elif Path('/usr/bin/chromium').exists(): options['executable_path']='/usr/bin/chromium'
    browser=p.chromium.launch(**options)
    page=browser.new_page(viewport={'width':1440,'height':1080})
    errors=[];requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.set_default_timeout(5000)
    page.set_content(HTML);page.wait_for_selector('.sv-art svg')
    check('two perspectives rendered',page.locator('.sv-grid > section').count()==2)
    check('refund arithmetic matches existing Figma quote','1,100.000 LYD' in page.locator('#refund-amount').inner_text())
    check('consent is unchecked by default',not page.locator('#consent').is_checked())
    check('request disabled before consent',page.locator('#request-cancel').is_disabled())
    check('provider events unavailable before request',page.locator('#supplier-cancelled').is_disabled())
    page.locator('#consent').check()
    check('checkbox retains focus after render',page.evaluate('document.activeElement.id')=='consent')
    check('request enabled after explicit consent',page.locator('#request-cancel').is_enabled())
    page.locator('#request-cancel').click()
    check('request has not cancelled booking',page.locator('#customer-state').inner_text()=='Cancellation requested')
    check('no second request button',page.locator('#request-cancel').count()==0)
    check('focus moves to current outcome',page.evaluate('document.activeElement.id')=='customer-state')
    check('refund cannot skip supplier confirmation',page.locator('#refund-confirmed').is_disabled())
    page.locator('#supplier-cancelled').click()
    check('cancellation not refund','Supplier cancelled' in page.locator('#customer-state').inner_text())
    page.locator('#refund-processing').click()
    check('pending refund separate','Refund processing' in page.locator('#customer-state').inner_text())
    page.screenshot(path=str(OUT/'orbit-refund-processing.png'),full_page=True)
    page.locator('#refund-confirmed').click()
    check('credit confirmed only after evidence','Refund confirmed' in page.locator('#customer-state').inner_text())
    check('closed booking cannot cancel again',page.locator('#request-cancel').count()==0)
    page.locator('#world-move').click();page.locator('#submit-driver').click()
    check('driver submission remains in review','Verification in review' in page.locator('#customer-state').inner_text())
    check('unapproved driver blocked',page.locator('#go-online').is_disabled())
    check('approval blocked without checklist and note',page.locator('#queue-approve').is_disabled())
    page.locator('#review-note').fill('Identity, licence and vehicle match.')
    check('note alone cannot approve',page.locator('#queue-approve').is_disabled())
    for name in ['identity','licence','insurance']:page.locator('#check-'+name).check()
    check('approval enabled after evidence and note',page.locator('#queue-approve').is_enabled())
    page.locator('#queue-approve').click()
    check('queueing is not approving','Verification in review' in page.locator('#customer-state').inner_text())
    check('queued decision cannot dispatch',page.locator('#go-online').is_disabled())
    page.locator('#apply-decision').click()
    check('acknowledged approval remains offline','Approved · offline' in page.locator('#customer-state').inner_text())
    check('eligible driver may choose online',page.locator('#go-online').is_enabled())
    page.locator('#go-online').click()
    check('online requires driver action','Online · demo' in page.locator('#customer-state').inner_text())
    page.locator('#advance-time').click()
    check('stale snapshot disables availability',page.locator('#go-online').is_disabled())
    page.locator('summary').filter(has_text='Freshness').click();page.locator('#refresh-status').click()
    check('freshness refresh does not reconnect','Approved · offline' in page.locator('#customer-state').inner_text())
    page.locator('summary').filter(has_text='Freshness').click();page.locator('#suspend').click()
    check('suspension blocks self-clear upload',page.locator('#replace-licence').is_disabled())
    page.locator('#world-orbit').click()
    check('changing product preserves its case','Refund confirmed' in page.locator('#customer-state').inner_text())
    page.locator('#reset-case').click();page.locator('#consent').check();page.locator('#advance-time').click()
    check('expired quote blocks cancellation',page.locator('#request-cancel').is_disabled())
    page.locator('#refresh-quote').click()
    check('new quote clears consent',not page.locator('#consent').is_checked())
    check('renewed quote needs new consent',page.locator('#request-cancel').is_disabled())
    page.locator('#world-move').click();page.locator('#submit-driver').click();page.locator('#review-note').fill('Licence photo is blurred.')
    page.locator('#queue-correct').click();page.locator('#apply-decision').click()
    check('correction reaches driver','Correction requested' in page.locator('#customer-state').inner_text())
    page.locator('#replace-licence').click();page.locator('#submit-driver').click()
    check('replacement clears the review checklist',not page.locator('#check-licence').is_checked())
    page.locator('#review-note').fill('Current replacement needs careful review.')
    page.locator('#locale').select_option('ar');page.locator('#mode').select_option('dark')
    check('Arabic direction is structural',page.locator('html').get_attribute('dir')=='rtl')
    check('locale change preserves typed review note',page.locator('#review-note').input_value()=='Current replacement needs careful review.')
    check('dark mode enabled',page.locator('html').get_attribute('data-mode')=='dark')
    check('IDs are directionally isolated',page.locator('.sv-row bdi').first.get_attribute('dir')=='ltr')
    page.locator('#reduced').check()
    check('reduced motion enabled',page.locator('html').get_attribute('data-motion')=='reduced')
    check('no decorative animations under reduced motion',page.evaluate('document.getAnimations().filter(a=>a.playState==="running").length')==0)
    page.screenshot(path=str(OUT/'move-review-ar-dark.png'),full_page=True)
    for width in [390,768,1440]:
        page.set_viewport_size({'width':width,'height':950})
        check(f'Arabic dark layout fits {width}px',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
        if width==390:page.screenshot(path=str(OUT/'move-mobile-ar-dark.png'),full_page=True)
    page.locator('#world-orbit').click();page.set_viewport_size({'width':390,'height':950})
    check('Orbit narrow Arabic layout fits',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
    page.screenshot(path=str(OUT/'orbit-mobile-ar-dark.png'),full_page=True)
    page.locator('#locale').select_option('en');page.locator('#mode').select_option('light')
    check('English narrow layout fits',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
    check('browser has no JavaScript errors',not errors)
    check('offline artifact makes no network requests',not requests)
    version=browser.version;browser.close()
report={'scope':'Offline Chromium functional and responsive checks; not a WCAG certification or full workspace CI.','browser':version,'passed':sum(x['passed'] for x in results),'failed':sum(not x['passed'] for x in results),'checks':results,'pageErrors':errors,'requests':requests}
(OUT/'servicing-browser-report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False))
print(json.dumps({'passed':report['passed'],'failed':report['failed'],'browser':version}))
