#!/usr/bin/env python3
"""Emit per-bank Odyssey icon sets from the shared roster.

One roster, three banks, and **a different professionally drawn icon family per
bank** — chosen because its house style is that bank's charter entry, not because
it happens to look different:

  Andalus  Phosphor        (MIT)         rounded terminals, generous counters, and
                                         the only high-coverage family that ships
                                         `fill` as its own drawn weight, which is
                                         what this bank's filled selected state needs
  Nuran    Carbon / IBM    (Apache-2.0)  flat terminals, orthogonal, the thinnest ink
                                         of the three: the documentary set
  FGLB     Material Symbols Outlined 600 (Apache-2.0)  a 20dp live area inside a 24dp
                                         box, so spaciousness is the grid itself

The reasoning, the survey that rejected the other ten families, and the licence
findings are in `docs/design/PER_BANK_ICON_LIBRARIES.md`.

**The per-bank difference is SELECTION, carried as data in `library_map.json`.**
There is no per-bank branch anywhere below this line, and no bank restyles another
bank's drawing — that was the earlier approach and it was rejected, because changing
the stroke of one drawing is a filter, not a vocabulary.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LIBROOT = os.environ.get("ICONLIBS", "/tmp/iconlibs")

# library -> (asset directory, transform onto the 0 0 24 24 box, how it is painted)
#
# All three primary families are FILLED-PATH sets: the "outline" look is drawn as a
# closed shape, not stroked. That is why they need no stroke tuning and cannot be
# given any — see the note on the profiles below.
LIBS = {
    "phosphor":      (f"{LIBROOT}/x_phosphor-icons-core/package/assets/regular", "scale(0.09375)", "fill"),
    "phosphor_fill": (f"{LIBROOT}/x_phosphor-icons-core/package/assets/fill",    "scale(0.09375)", "fill"),
    "carbon":        (f"{LIBROOT}/x_carbon-icons/package/svg/32",                "scale(0.75)",    "fill"),
    "msym":          (f"{LIBROOT}/x_msym600/package/outlined",                   "scale(0.025) translate(0 960)", "fill"),
    # the stroke-drawn gap-fillers
    "tabler":        (f"{LIBROOT}/tabler/icons/outline",                         "scale(1)", "stroke"),
    "iconoir":       (f"{LIBROOT}/x_iconoir/package/icons/regular",              "scale(1)", "stroke"),
    "lucide":        (f"{LIBROOT}/lucide/icons",                                 "scale(1)", "stroke"),
}

PROFILES = {
    # libs:         this bank's family first, then its declared gap-filler, then Lucide.
    #               A gap is NEVER filled from another bank's family: filling Nuran's
    #               missing credit card from Material Sharp made Nuran and FGLB draw
    #               the identical card, because Sharp and Outlined are the same paths.
    # scale:        optical size — how much of the 24 box the glyph claims.
    # filledActive: does this bank's selected state use a natively FILLED glyph?
    # gap*:         terminal treatment for the STROKE-DRAWN gap-fillers only. The three
    #               primary families are filled-path sets, so these never reach them —
    #               they are not the old per-bank stroke filter and must not become it.
    #               They exist so a Tabler or Iconoir fill-in sits inside its bank's
    #               vocabulary instead of announcing itself.
    "andalus": dict(libs=["phosphor", "tabler", "lucide"], scale=1.00, filledActive=True,
                    gapStroke=1.60, gapCap="round", gapJoin="round", gapMiter=4),
    "nuran":   dict(libs=["carbon", "iconoir", "lucide"],  scale=0.94, filledActive=False,
                    gapStroke=1.70, gapCap="butt",  gapJoin="miter", gapMiter=2),
    "fglb":    dict(libs=["msym", "lucide"],               scale=0.94, filledActive=False,
                    gapStroke=1.90, gapCap="butt",  gapJoin="miter", gapMiter=2),
}

# concept -> {bank: [library, glyph]}. Generated by tools/icons/resolve.py and then
# hand-corrected; the corrections are the design decisions and are recorded with
# their reason in the map's own `_why` block.
MAP = json.load(open(os.path.join(HERE, "library_map.json"), encoding="utf8"))

BODY = re.compile(r"<svg[^>]*>(.*)</svg>", re.S)
GUARD = re.compile(r'<(rect|path)\b[^>]*\bfill="none"[^>]*\bstroke="none"[^>]*/>')
ROUND_TERMINAL = re.compile(r'\s*stroke-line(cap|join)="[^"]*"')


def _fmt(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"


def load_inner(lib, name):
    d, _, _ = LIBS[lib]
    s = open(os.path.join(d, name + ".svg"), encoding="utf8").read()
    body = BODY.search(s).group(1)
    body = GUARD.sub("", body)              # Tabler's transparent 24x24 guard rect
    # A gap-filler's own terminals are dropped so the bank's profile decides them;
    # this is the ONLY thing a profile still tunes, and only on a stroked fill-in.
    return ROUND_TERMINAL.sub("", body).strip()


def paint_for(lib, p):
    if LIBS[lib][2] == "fill":
        return 'fill="currentColor"'
    return (f'fill="none" stroke="currentColor" stroke-width="{_fmt(p["gapStroke"])}" '
            f'stroke-linecap="{p["gapCap"]}" stroke-linejoin="{p["gapJoin"]}" '
            f'stroke-miterlimit="{p["gapMiter"]}"')


# `slash` and `renew` are Neptune's own two marks, drawn on top of a library glyph to
# say "blocked" and "renew". They carry their own paint because the glyph underneath
# may be a filled family or a stroked one, and an overlay that inherited either would
# vanish in the other.
SLASH = ('<path d="M4.6 19.4 19.4 4.6" fill="none" stroke="currentColor" '
         'stroke-width="1.9" stroke-linecap="round"/>')
RENEW = ('<g transform="translate(0.6 0.6) scale(0.8)">%s</g>'
         '<g fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" '
         'stroke-linejoin="round">'
         '<path d="M20.6 16.4a3 3 0 1 1-.9-2.1"/><path d="M20.9 12.4v2.3h-2.3"/></g>')


def resolve(bank, concept, filled):
    """The one place a bank name meets a glyph name, and it is a table lookup."""
    lib, name = MAP[concept][bank]
    if filled and lib == "phosphor":
        return "phosphor_fill", name + "-fill"
    return lib, name


def emit(bank, name, spec, roster):
    p = PROFILES[bank]
    cls = spec["class"]
    if cls == "mark":
        return None            # a partner's trademark is not raw material
    filled = False
    base = spec
    if cls == "alias":
        base = roster[spec["of"]]
        filled = bool(p["filledActive"] and base.get("sel"))
    concept = base["src"].split(":", 1)[1]
    lib, glyph = resolve(bank, concept, filled)

    s = p["scale"]
    _, tf, _ = LIBS[lib]
    # The library's own transform maps ITS grid onto the 24 box — Material's is
    # scale(0.025), Phosphor's scale(0.09375). Neptune's own overlays are drawn in
    # 24-unit coordinates, so they must sit OUTSIDE that transform: inside it the
    # slash on a blocked card shrank to a fortieth of its size and disappeared.
    body = f'<g transform="{tf}">{load_inner(lib, glyph)}</g>'
    ov = spec.get("overlay")
    if ov == "slash":
        body += SLASH
    elif ov == "renew":
        body = RENEW % body
    header = (f"<!-- Neptune Odyssey icon · bank={bank} · glyph={name}\n"
              f"     source={lib}:{glyph} · concept={concept} · optical scale={s}\n"
              f"     GENERATED by tools/icons/install.py — do not hand-edit.\n"
              f"     Licences: see assets/ICON_LICENSES.md -->\n")
    return (f'{header}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
            f'width="24" height="24" {paint_for(lib, p)}>'
            f'<g transform="translate(12 12) scale({_fmt(s)}) translate(-12 -12)">'
            f'{body}</g></svg>\n')


def main():
    roster = json.load(open(sys.argv[1]))
    outroots = json.loads(sys.argv[2])
    counts = {}
    for bank, root in outroots.items():
        os.makedirs(root, exist_ok=True)
        n = 0
        for name, spec in roster.items():
            svg = emit(bank, name, spec, roster)
            if svg is None:
                continue
            open(os.path.join(root, name + ".svg"), "w", encoding="utf8").write(svg)
            n += 1
        counts[bank] = n
    print(json.dumps(counts))


if __name__ == "__main__":
    main()
