#!/usr/bin/env python3
"""Build the three banks' icon sets into the Flutter app's asset roots.

Per-bank difference is ENTIRELY in PROFILES. Nothing below reads a bank name.
"""
import json, os, re, shutil, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import emit as E

APP = sys.argv[1]
ROSTER = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "roster.json")))
ROOTS = {"andalus": "assets/icons", "nuran": "assets/nuran/icons", "fglb": "assets/fglb/icons"}
SRC_MARKS = os.path.join(APP, "assets/icons")   # marks already live at their bank's own root

TAGSTRIP = re.compile(r'<(\?xml[^>]*\?|!--.*?--|!DOCTYPE[^>]*)>', re.S)
SVGROOT = re.compile(r'<svg([^>]*)>(.*)</svg>', re.S)
ATTRSTRIP = re.compile(r'\s(stroke-width|stroke-linecap|stroke-linejoin|stroke|fill|class|style)\s*=\s*"[^"]*"')

def normalise_existing(path, bank, name, kind):
    """Re-cut a glyph the bank already owns onto the Odyssey grid at its profile."""
    p = E.PROFILES[bank]
    s = TAGSTRIP.sub("", open(path, encoding="utf8", errors="replace").read())
    m = SVGROOT.search(s)
    attrs, inner = m.group(1), m.group(2)
    vb = re.search(r'viewBox="\s*([\d.\-]+)[ ,]+([\d.\-]+)[ ,]+([\d.\-]+)[ ,]+([\d.\-]+)', attrs)
    x0, y0, w, h = (float(g) for g in vb.groups()) if vb else (0, 0, 24, 24)
    k = 24.0 / max(w, h) * p["scale"]
    dx = 12 - (x0 + w / 2) * k
    dy = 12 - (y0 + h / 2) * k
    # per-element paint is dropped: the root carries the whole family's paint
    inner = ATTRSTRIP.sub("", inner)
    inner = re.sub(r'\s(fill|stroke)="none"', "", inner)
    g = (f'<g transform="translate({E._fmt(dx)} {E._fmt(dy)}) scale({E._fmt(k)})">'
         f'{inner.strip()}</g>')
    paint = (f'fill="none" stroke="currentColor" stroke-width="{E._fmt(p["stroke"]/k)}" '
             f'stroke-linecap="{p["cap"]}" stroke-linejoin="{p["join"]}" '
             f'stroke-miterlimit="{p["miter"]}"')
    header = (f"<!-- Neptune Odyssey icon · bank={bank} · glyph={name}\n"
              f"     source=own:{kind} — this bank's OWN drawing, re-cut onto the 24 grid at its\n"
              f"     profile (stroke={p['stroke']} cap={p['cap']} join={p['join']} scale={p['scale']}).\n"
              f"     GENERATED by tools/icons/install.py — do not hand-edit. -->\n")
    return (f'{header}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
            f'width="24" height="24" {paint}>{g}</svg>\n')

def classify(path):
    s = open(path, encoding="utf8", errors="replace").read()
    has_stroke = bool(re.search(r'stroke="(?!none)[^"]+"', s)) or bool(re.search(r'stroke:', s))
    fills = re.findall(r'fill="([^"]+)"', s) + re.findall(r'fill:\s*([^;"\s]+)', s)
    solid = [x for x in fills if x.lower() not in ("none", "#fff", "#ffffff", "white", "transparent")]
    return "STROKE" if (has_stroke and not solid) else ("FILL" if solid and not has_stroke else
           ("MIXED" if has_stroke and solid else "NONE"))

def main():
    report = {b: {"kept": [], "generated": [], "mark": [], "removed": []} for b in ROOTS}
    for bank, rel in ROOTS.items():
        root = os.path.join(APP, rel)
        os.makedirs(root, exist_ok=True)
        want = set()
        for name, spec in ROSTER.items():
            cls = spec["class"]
            if cls == "mark":
                if bank not in spec["banks"]:
                    continue
                want.add(name + ".svg")
                src = os.path.join(root, name + ".svg")
                if not os.path.exists(src):
                    src = os.path.join(SRC_MARKS, name + ".svg")
                if os.path.abspath(src) != os.path.abspath(os.path.join(root, name + ".svg")):
                    shutil.copyfile(src, os.path.join(root, name + ".svg"))
                report[bank]["mark"].append(name)
                continue
            want.add(name + ".svg")
            out = os.path.join(root, name + ".svg")
            existing = os.path.join(root, name + ".svg")
            # A bank keeps its own drawing when it HAS one and that drawing is
            # already an outline. A filled UI glyph cannot be un-filled
            # mechanically, so it is re-drawn from the shared roster instead —
            # that swap IS the consistency fix.
            # Idempotence: a file we already emitted says so in its header, so a
            # re-run never mistakes our own output for the bank's original drawing.
            prior = open(existing, encoding="utf8", errors="replace").read(400) if os.path.exists(existing) else ""
            if "source=own:" in prior and f"bank={bank}" in prior:
                report[bank]["kept"].append(name)
                continue
            keep = ("source=" not in prior and E.PROFILES[bank]["keepOwnDrawings"]
                    and os.path.exists(existing)
                    and classify(existing) == "STROKE"
                    and not (cls == "alias" and E.PROFILES[bank]["filledActive"]))
            if keep:
                svg = normalise_existing(existing, bank, name, "outline")
                report[bank]["kept"].append(name)
            else:
                svg = E.emit(bank, name, spec, ROSTER)
                report[bank]["generated"].append(name)
            open(out, "w", encoding="utf8").write(svg)
        for f in sorted(os.listdir(root)):
            # A raster in a vector icon set is the same defect as a filled glyph
            # in an outline set: nothing references these and they cannot follow
            # the profile. The roster is SVG-only, so a .png here is always stale.
            if f.endswith(".png") or (f.endswith(".svg") and f not in want):
                os.remove(os.path.join(root, f))
                report[bank]["removed"].append(f)
    json.dump(report, open("/tmp/gen/install_report.json", "w"), indent=1)
    for b, r in report.items():
        print(f"{b:8} kept={len(r['kept']):3} generated={len(r['generated']):3} "
              f"marks={len(r['mark']):2} removed={len(r['removed']):2}")

if __name__ == "__main__":
    main()
