// Scoped regression checks; compile the real canonical experience dependency with the new module.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const temp = mkdtempSync(join(tmpdir(), 'odyssey-servicing-'));
const results = [];
const check = (name, fn) => { try { fn(); results.push({ name, passed: true }); } catch (e) { results.push({ name, passed: false, error: e.message }); } };
try {
  const source = fileURLToPath(new URL('../src/servicing.ts', import.meta.url));
  const compile = spawnSync(process.platform === 'win32' ? 'tsc.cmd' : 'tsc', [source, '--target','ES2022','--module','ES2022','--moduleResolution','Bundler','--strict','--skipLibCheck','--outDir',temp], { encoding: 'utf8' });
  if (compile.error || compile.status !== 0) throw new Error(`TypeScript failed: ${compile.error ?? ''}\n${compile.stdout}\n${compile.stderr}`);
  writeFileSync(join(temp, 'package.json'), '{"type":"module"}');
  const m = await import(pathToFileURL(join(temp, 'servicing.js')).href);
  const e = await import(pathToFileURL(join(temp, 'experience.js')).href);
  const money = (minor, currency='LYD', scale=3) => ({ minor, currency, scale });
  const booking = { reference:'OR-DEMO-021', revision:'v1', state:'confirmed', originalPayment:money(1250000n) };
  const quote = { reference:'CQ-021', bookingReference:booking.reference, bookingRevision:'v1', issuedAtMs:1000, expiresAtMs:2000, originalPayment:money(1250000n), supplierPenalty:money(125000n), agencyFee:money(25000n), returnTo:'original-payment-method' };
  const consent = { accepted:true, quoteReference:quote.reference, bookingReference:booking.reference, bookingRevision:'v1' };
  const review = () => m.reviewCancellation(booking, quote, 1500);
  check('Original six Odyssey worlds preserved', () => assert.deepEqual(e.VISUAL_WORLDS, ['orbit','current','bloom','atelier','signal','horizon']));
  check('Orbit remains the product, Voyage remains its recipe', () => assert.equal(e.PRODUCT_GRAMMARS.travel.appearanceRecipe, 'voyage'));
  check('Exact 1250 - 125 - 25 = 1100 LYD refund', () => { const r=review(); assert.equal(r.estimatedRefund.minor,1100000n); assert.equal(r.retainedFees.minor,150000n); });
  check('Cancellation review is immutable and leaves booking unchanged', () => { assert.ok(Object.isFrozen(review().estimatedRefund)); assert.equal(booking.state,'confirmed'); });
  check('Quote valid one millisecond before expiry', () => assert.equal(m.reviewCancellation(booking,quote,1999).estimatedRefund.minor,1100000n));
  check('Quote expires at exact boundary', () => assert.throws(()=>m.reviewCancellation(booking,quote,2000)));
  check('Future-issued quotes are rejected', () => assert.throws(()=>m.reviewCancellation(booking,quote,999)));
  check('Malformed clock fails', () => [NaN,Infinity,-1,1.5].forEach(now=>assert.throws(()=>m.reviewCancellation(booking,quote,now))));
  check('Wrong booking reference fails', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,bookingReference:'OTHER'},1500)));
  check('Stale booking revision fails', () => assert.throws(()=>m.reviewCancellation({...booking,revision:'v2'},quote,1500)));
  check('Original payment mismatch fails', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,originalPayment:money(1200000n)},1500)));
  check('Negative fees fail', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,agencyFee:money(-1n)},1500)));
  check('Fees exceeding payment fail', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,agencyFee:money(1250001n)},1500)));
  check('Mixed currencies fail', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,agencyFee:money(25000n,'USD')},1500)));
  check('Mixed scales fail', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,agencyFee:money(25000n,'LYD',2)},1500)));
  check('Floating-point money fails', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,agencyFee:money(25.5)},1500)));
  check('Redirected refunds fail', () => assert.throws(()=>m.reviewCancellation(booking,{...quote,returnTo:'other-wallet'},1500)));
  check('Zero-fee refund is explicit and exact', () => assert.equal(m.reviewCancellation(booking,{...quote,supplierPenalty:money(0n),agencyFee:money(0n)},1500).estimatedRefund.minor,1250000n));
  check('Zero refund is allowed when disclosed fees equal payment', () => assert.equal(m.reviewCancellation(booking,{...quote,supplierPenalty:money(1250000n),agencyFee:money(0n)},1500).estimatedRefund.minor,0n));
  check('Accepted current quote creates only cancel_requested', () => assert.equal(m.requestCancellation(booking,quote,consent,1500).state,'cancel_requested'));
  check('Consent must be Boolean true', () => [false,'true',undefined].forEach(accepted=>assert.throws(()=>m.requestCancellation(booking,quote,{...consent,accepted},1500))));
  check('Consent must match the shown quote and revision', () => { assert.throws(()=>m.requestCancellation(booking,quote,{...consent,quoteReference:'OLD'},1500)); assert.throws(()=>m.requestCancellation(booking,quote,{...consent,bookingRevision:'v0'},1500)); });
  check('Pending cancellation cannot be resubmitted', () => assert.throws(()=>m.requestCancellation({...booking,state:'cancel_requested'},quote,consent,1500)));
  check('Quote revalidated at submission', () => assert.throws(()=>m.requestCancellation(booking,quote,consent,2000)));
  check('Provider cancellation remains distinct from refund', () => assert.equal(m.advanceAftercare('cancel_requested',{type:'CANCELLED',authority:'provider',reference:'CX-021'}),'cancelled'));
  check('Only provider with reference may confirm aftercare', () => { assert.throws(()=>m.advanceAftercare('cancel_requested',{type:'CANCELLED',authority:'user',reference:'CX'})); assert.throws(()=>m.advanceAftercare('cancel_requested',{type:'CANCELLED',authority:'provider'})); });
  check('Cannot skip refund processing', () => assert.throws(()=>m.advanceAftercare('cancelled',{type:'REFUNDED',authority:'provider',reference:'RF'})));
  check('Refund processing then confirmed credit completes normally', () => { const p=m.advanceAftercare('cancelled',{type:'REFUND_PENDING',authority:'provider',reference:'RF'}); assert.equal(m.advanceAftercare(p,{type:'REFUNDED',authority:'provider',reference:'RF'}),'refunded'); });
  const requirements=[{kind:'identity',expiryRequired:false},{kind:'licence',expiryRequired:true},{kind:'insurance',expiryRequired:true}];
  let draft=m.newDriverReview('DR-1','VEH-1');
  const docs=[{kind:'identity',reference:'ID-1',expiresAtMs:null},{kind:'licence',reference:'DL-1',expiresAtMs:5000},{kind:'insurance',reference:'IN-1',expiresAtMs:4000}];
  const context={enabled:true,nowMs:1500,snapshotFreshUntilMs:2500,requirements};
  check('New driver is not online-eligible', () => assert.equal(m.canDriverGoOnline(draft,context),false));
  check('Missing required document blocks submission', () => assert.throws(()=>m.submitDriverReview(draft,requirements,1500)));
  for(const d of docs) draft=m.recordDriverDocument(draft,d);
  check('Uploaded documents do not imply approval', () => { assert.equal(draft.status,'draft'); assert.equal(draft.revision,3); assert.equal(m.canDriverGoOnline(draft,context),false); });
  check('Snapshots copy and freeze documents', () => { assert.ok(Object.isFrozen(draft.documents)); assert.ok(Object.isFrozen(draft.documents[0])); assert.notEqual(draft.documents[0],docs[0]); });
  check('No operator requirements fails closed', () => assert.throws(()=>m.submitDriverReview(draft,[],1500)));
  check('Duplicate requirements rejected', () => assert.throws(()=>m.submitDriverReview(draft,[requirements[0],requirements[0]],1500)));
  check('Insurance must have an expiry when required', () => { const d=m.recordDriverDocument(draft,{...docs[2],expiresAtMs:null}); assert.throws(()=>m.submitDriverReview(d,requirements,1500)); });
  check('Expired document blocks submission at boundary', () => assert.throws(()=>m.submitDriverReview(draft,requirements,4000)));
  const pending=m.submitDriverReview(draft,requirements,1500);
  const decision={authority:'provider',driverReference:'DR-1',vehicleReference:'VEH-1',revision:3,reviewReference:'REVIEW-1',result:'approved',approvedUntilMs:3000};
  check('Submitted review stays unavailable', () => { assert.equal(pending.status,'in_review'); assert.equal(m.canDriverGoOnline(pending,context),false); });
  check('Review cannot be submitted twice', () => assert.throws(()=>m.submitDriverReview(pending,requirements,1500)));
  check('Pending review blocks silent document replacement', () => assert.throws(()=>m.recordDriverDocument(pending,docs[0])));
  check('User approval cannot unlock driving', () => assert.throws(()=>m.applyDriverDecision(pending,{...decision,authority:'user'},requirements,1500)));
  check('Wrong driver, vehicle or document revision rejected', () => { for(const p of [{driverReference:'OTHER'},{vehicleReference:'OTHER'},{revision:2}]) assert.throws(()=>m.applyDriverDecision(pending,{...decision,...p},requirements,1500)); });
  check('Approval requires a provider review reference', () => assert.throws(()=>m.applyDriverDecision(pending,{...decision,reviewReference:''},requirements,1500)));
  check('Approval requires a future validity boundary', () => [undefined,1500,NaN].forEach(approvedUntilMs=>assert.throws(()=>m.applyDriverDecision(pending,{...decision,approvedUntilMs},requirements,1500))));
  const approved=m.applyDriverDecision(pending,decision,requirements,1500);
  check('Approved current driver may request online availability', () => assert.equal(m.canDriverGoOnline(approved,context),true));
  check('Approval is immutable and does not mutate pending snapshot', () => { assert.equal(pending.status,'in_review'); assert.equal(approved.status,'approved'); assert.ok(Object.isFrozen(approved)); });
  check('Replayed approval is rejected', () => assert.throws(()=>m.applyDriverDecision(approved,decision,requirements,1500)));
  check('Disabled operator capability fails closed', () => [false,'true',undefined].forEach(enabled=>assert.equal(m.canDriverGoOnline(approved,{...context,enabled}),false)));
  check('Stale server snapshot fails at exact boundary', () => assert.equal(m.canDriverGoOnline(approved,{...context,nowMs:2500}),false));
  check('Expired approval fails even with fresh state', () => assert.equal(m.canDriverGoOnline(approved,{...context,nowMs:3000,snapshotFreshUntilMs:5000}),false));
  check('Expired insurance fails despite longer approval', () => { const long=m.applyDriverDecision(pending,{...decision,approvedUntilMs:6000},requirements,1500); assert.equal(m.canDriverGoOnline(long,{...context,nowMs:4000,snapshotFreshUntilMs:6000}),false); });
  check('Updating a document revokes prior UI approval', () => { const updated=m.recordDriverDocument(approved,{...docs[2],reference:'IN-2',expiresAtMs:8000}); assert.equal(updated.status,'draft'); assert.equal(updated.reviewReference,null); assert.equal(m.canDriverGoOnline(updated,context),false); });
  check('Needs-action can resubmit and cannot go online', () => { const action=m.applyDriverDecision(pending,{...decision,result:'needs_action'},requirements,1500); assert.equal(m.canDriverGoOnline(action,context),false); const updated=m.recordDriverDocument(action,{...docs[1],reference:'DL-2'}); assert.equal(m.submitDriverReview(updated,requirements,1500).status,'in_review'); });
  check('Suspension stops eligibility immediately', () => { const suspended=m.applyDriverDecision(approved,{...decision,result:'suspended'},requirements,1500); assert.equal(m.canDriverGoOnline(suspended,context),false); });
  check('Malformed snapshots and invalid clocks return false', () => { assert.equal(m.canDriverGoOnline({...approved,status:'constructor'},context),false); assert.equal(m.canDriverGoOnline(null,context),false); assert.equal(m.canDriverGoOnline(approved,{...context,nowMs:NaN}),false); });
  check('Duplicate document kinds cannot bypass checks', () => assert.equal(m.canDriverGoOnline({...approved,documents:[...approved.documents,approved.documents[0]]},context),false));
  const failed=results.filter(x=>!x.passed).length;
  console.log(JSON.stringify({typecheck:'passed',total:results.length,passed:results.length-failed,failed,results},null,2));
  if(failed)process.exitCode=1;
} finally { rmSync(temp,{recursive:true,force:true}); }
