// © 2026 Neptune.Fintech (neptune.ly) · Neptune Odyssey Community License v1.0
//
// :odyssey-tokens — the determinism backbone, pure Kotlin (stdlib only).
// Ports of the OKLCH↔sRGB math, the seed→M3 palette ramp, and the brandprint
// codec, golden-tested against build/tokens.resolved.json and the four
// reference brandprints (see roadmap/ROADMAP.md promotion bar).
// BrandData.g.kt is GENERATED by tools/codegen.mjs — never hand-edited.

import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKmpLibrary)
    `maven-publish`
}

kotlin {
    explicitApi()
    jvmToolchain(17)

    jvm()
    androidLibrary {
        namespace = "ly.neptune.odyssey.tokens"
        compileSdk = 36
        minSdk = 24
    }
    // No iosX64: Compose Multiplatform 1.11 dropped Intel-simulator
    // artifacts, and the ui module must ship the same target set.
    iosArm64()
    iosSimulatorArm64()
    js {
        nodejs()
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}
