// Generated opt-in Material 3 colour/shape adapter. Supply bundled font families in the host.
package ly.neptune.odyssey.livingworlds

import androidx.compose.material3.*
import androidx.compose.ui.graphics.Color
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp

public fun odyssey3Colors(brand: String = "Clarity", dark: Boolean = false): ColorScheme = when (brand to dark) {
    ("Clarity" to false) -> lightColorScheme(
        primary = Color(0xFF216BED),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEAF0FF),
        onPrimaryContainer = Color(0xFF07315F),
        surface = Color(0xFFFAF9F5),
        onSurface = Color(0xFF142238),
        onSurfaceVariant = Color(0xFF546174),
        outline = Color(0xFF77828C),
        outlineVariant = Color(0xFFDCDCD6),
        error = Color(0xFFAC292C),
        errorContainer = Color(0xFFFDEDEB),
        onErrorContainer = Color(0xFFAC292C),
        onError = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF216BED),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEAF0FF),
        onSecondaryContainer = Color(0xFF07315F),
    )
    ("Clarity" to true) -> darkColorScheme(
        primary = Color(0xFFA9C8FF),
        onPrimary = Color(0xFF07315F),
        primaryContainer = Color(0xFF163A76),
        onPrimaryContainer = Color(0xFFA9C8FF),
        surface = Color(0xFF111821),
        onSurface = Color(0xFFF3F1EA),
        onSurfaceVariant = Color(0xFFBFC9D4),
        outline = Color(0xFF596B80),
        outlineVariant = Color(0xFF253240),
        error = Color(0xFFFFB4AC),
        errorContainer = Color(0xFF492729),
        onErrorContainer = Color(0xFFFFB4AC),
        onError = Color(0xFF492729),
        surfaceContainer = Color(0xFF1B2530),
        secondary = Color(0xFFA9C8FF),
        onSecondary = Color(0xFF07315F),
        secondaryContainer = Color(0xFF163A76),
        onSecondaryContainer = Color(0xFFA9C8FF),
    )
    ("Reserve" to false) -> lightColorScheme(
        primary = Color(0xFF114075),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEAF2F5),
        onPrimaryContainer = Color(0xFF07315F),
        surface = Color(0xFFFAF9F5),
        onSurface = Color(0xFF142238),
        onSurfaceVariant = Color(0xFF546174),
        outline = Color(0xFF77828C),
        outlineVariant = Color(0xFFDCDCD6),
        error = Color(0xFFAC292C),
        errorContainer = Color(0xFFFDEDEB),
        onErrorContainer = Color(0xFFAC292C),
        onError = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF114075),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEAF2F5),
        onSecondaryContainer = Color(0xFF07315F),
    )
    ("Reserve" to true) -> darkColorScheme(
        primary = Color(0xFFB4CDEA),
        onPrimary = Color(0xFF07315F),
        primaryContainer = Color(0xFF173957),
        onPrimaryContainer = Color(0xFFB4CDEA),
        surface = Color(0xFF111821),
        onSurface = Color(0xFFF3F1EA),
        onSurfaceVariant = Color(0xFFBFC9D4),
        outline = Color(0xFF596B80),
        outlineVariant = Color(0xFF253240),
        error = Color(0xFFFFB4AC),
        errorContainer = Color(0xFF492729),
        onErrorContainer = Color(0xFFFFB4AC),
        onError = Color(0xFF492729),
        surfaceContainer = Color(0xFF1B2530),
        secondary = Color(0xFFB4CDEA),
        onSecondary = Color(0xFF07315F),
        secondaryContainer = Color(0xFF173957),
        onSecondaryContainer = Color(0xFFB4CDEA),
    )
    ("Drive" to false) -> lightColorScheme(
        primary = Color(0xFF125545),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDCF3DE),
        onPrimaryContainer = Color(0xFF07315F),
        surface = Color(0xFFFAF9F5),
        onSurface = Color(0xFF142238),
        onSurfaceVariant = Color(0xFF546174),
        outline = Color(0xFF77828C),
        outlineVariant = Color(0xFFDCDCD6),
        error = Color(0xFFAC292C),
        errorContainer = Color(0xFFFDEDEB),
        onErrorContainer = Color(0xFFAC292C),
        onError = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF125545),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDCF3DE),
        onSecondaryContainer = Color(0xFF07315F),
    )
    ("Drive" to true) -> darkColorScheme(
        primary = Color(0xFFA9E0BC),
        onPrimary = Color(0xFF07315F),
        primaryContainer = Color(0xFF173E32),
        onPrimaryContainer = Color(0xFFA9E0BC),
        surface = Color(0xFF111821),
        onSurface = Color(0xFFF3F1EA),
        onSurfaceVariant = Color(0xFFBFC9D4),
        outline = Color(0xFF596B80),
        outlineVariant = Color(0xFF253240),
        error = Color(0xFFFFB4AC),
        errorContainer = Color(0xFF492729),
        onErrorContainer = Color(0xFFFFB4AC),
        onError = Color(0xFF492729),
        surfaceContainer = Color(0xFF1B2530),
        secondary = Color(0xFFA9E0BC),
        onSecondary = Color(0xFF07315F),
        secondaryContainer = Color(0xFF173E32),
        onSecondaryContainer = Color(0xFFA9E0BC),
    )
    ("Orbit" to false) -> lightColorScheme(
        primary = Color(0xFF07315F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFF3BB),
        onPrimaryContainer = Color(0xFF07315F),
        surface = Color(0xFFFAF9F5),
        onSurface = Color(0xFF142238),
        onSurfaceVariant = Color(0xFF546174),
        outline = Color(0xFF77828C),
        outlineVariant = Color(0xFFDCDCD6),
        error = Color(0xFFAC292C),
        errorContainer = Color(0xFFFDEDEB),
        onErrorContainer = Color(0xFFAC292C),
        onError = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF07315F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFF3BB),
        onSecondaryContainer = Color(0xFF07315F),
    )
    ("Orbit" to true) -> darkColorScheme(
        primary = Color(0xFFB9DDF5),
        onPrimary = Color(0xFF07315F),
        primaryContainer = Color(0xFF283749),
        onPrimaryContainer = Color(0xFFB9DDF5),
        surface = Color(0xFF111821),
        onSurface = Color(0xFFF3F1EA),
        onSurfaceVariant = Color(0xFFBFC9D4),
        outline = Color(0xFF596B80),
        outlineVariant = Color(0xFF253240),
        error = Color(0xFFFFB4AC),
        errorContainer = Color(0xFF492729),
        onErrorContainer = Color(0xFFFFB4AC),
        onError = Color(0xFF492729),
        surfaceContainer = Color(0xFF1B2530),
        secondary = Color(0xFFB9DDF5),
        onSecondary = Color(0xFF07315F),
        secondaryContainer = Color(0xFF283749),
        onSecondaryContainer = Color(0xFFB9DDF5),
    )
    else -> error("Unknown Odyssey identity: $brand")
}

public fun odyssey3Shapes(brand: String): Shapes = Shapes(
    small = RoundedCornerShape(4.dp),
    medium = RoundedCornerShape((when (brand) { "Clarity" -> 12; "Reserve" -> 8; "Drive" -> 24; "Orbit" -> 20; else -> error("Unknown identity") }).dp),
    large = RoundedCornerShape((when (brand) { "Clarity" -> 16; "Reserve" -> 12; "Drive" -> 28; "Orbit" -> 24; else -> error("Unknown identity") }).dp),
)
