"""Regenerate portable Odyssey 3 tokens. Python standard library only."""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent
spec = json.loads((ROOT / 'tokens/odyssey.tokens.json').read_text())
tokens = {t['name']: t for t in spec['tokens']}

def resolve(name, brand='Clarity', appearance='Light', language='English', motion='Full'):
    t = tokens[name]
    mode = {'Palette':'Value','Dimensions':'Value','Identity':brand,'Theme':appearance,'Typography':language,'Motion':motion}[t['collection']]
    v = t['values'][mode]
    return resolve(v[1:-1], brand, appearance, language, motion) if isinstance(v,str) and v.startswith('{') else v

def css_value(t, value):
    if t['type']=='FLOAT':
        return str(value) + ('ms' if t['collection']=='Motion' else '' if t['name'].endswith('Coverage') else 'px')
    return json.dumps(value) if t['type']=='STRING' else value

def dtcg(t, value):
    if t['type']=='COLOR':
        return {'$type':'color','$value':{'colorSpace':'srgb','components':[round(int(value[i:i+2],16)/255,7) for i in (1,3,5)],'alpha':1,'hex':value}}
    if t['type']=='STRING': return {'$type':'fontFamily','$value':[value]}
    kind = 'duration' if t['collection']=='Motion' else 'number' if t['name'].endswith('Coverage') else 'dimension'
    return {'$type':kind,'$value':value if kind=='number' else {'value':value,'unit':'ms' if kind=='duration' else 'px'}}

resolved = {}
css = ['/* Generated by generate.py. Change the source JSON, not this file. */']
dt = {'$description':'Odyssey 3; resolved brand/mode sets for portable DTCG 2025.10 import.'}
for brand in spec['brands']:
    resolved[brand] = {}
    for appearance in ('Light','Dark'):
        values = {name:resolve(name,brand,appearance) for name in tokens}
        resolved[brand][appearance] = values
        selector = ':root, ' if brand==spec['brands'][0] and appearance=='Light' else ''
        selector += f'[data-brand="{brand}"][data-mode="{appearance.lower()}"]'
        css.append(selector+' {\n'+'\n'.join(f'  {tokens[n]["css"]}: {css_value(tokens[n],v)};' for n,v in values.items())+'\n}')
        group = {}
        for name, value in values.items():
            parent = group
            parts = name.split('/')
            for p in parts[:-1]: parent = parent.setdefault(p,{})
            parent[parts[-1]] = dtcg(tokens[name], value)
        dt.setdefault(brand,{})[appearance] = group
css.append('[data-brand][data-mode][lang="ar"] {\n'+ '\n'.join(f'  {t["css"]}: {css_value(t,resolve(t["name"],language="Arabic"))};' for t in spec['tokens'] if t['collection']=='Typography')+'\n}')
css.append('@media (prefers-reduced-motion: reduce) { :root {\n'+ '\n'.join(f'  {t["css"]}: 0ms !important;' for t in spec['tokens'] if t['collection']=='Motion')+'\n}}')
(ROOT/'tokens/odyssey.css').write_text('\n'.join(css)+'\n')
(ROOT/'tokens/resolved.json').write_text(json.dumps(resolved,indent=2)+'\n')
(ROOT/'tokens/odyssey.dtcg.json').write_text(json.dumps(dt,indent=2)+'\n')

def luminance(color):
    channels=[int(color[i:i+2],16)/255 for i in (1,3,5)]
    return sum((c/12.92 if c<=0.04045 else ((c+0.055)/1.055)**2.4)*w for c,w in zip(channels,[.2126,.7152,.0722]))
def ratio(a,b):
    x,y=sorted([luminance(a),luminance(b)])
    return (y+.05)/(x+.05)
pairs=[('color/onSurface','color/surface',4.5),('color/onSurfaceVariant','color/surface',4.5),('color/onPrimary','color/primary',4.5),('color/onPrimaryContainer','color/primaryContainer',4.5),('brand/onPlate','brand/plate',4.5),('brand/onHero','brand/hero',4.5),('color/success','color/successContainer',4.5),('color/warning','color/warningContainer',4.5),('color/error','color/errorContainer',4.5),('color/outline','color/surface',3)]
report=[]
for brand,modes in resolved.items():
    for mode,v in modes.items():
        for fg,bg,minimum in pairs:
            r=ratio(v[fg],v[bg]); report.append({'brand':brand,'mode':mode,'foreground':fg,'background':bg,'ratio':round(r,2),'minimum':minimum,'pass':r>=minimum})
(ROOT/'tokens/contrast-report.json').write_text(json.dumps(report,indent=2)+'\n')

roles={'primary':'primary','onPrimary':'onPrimary','primaryContainer':'primaryContainer','onPrimaryContainer':'onPrimaryContainer','surface':'surface','onSurface':'onSurface','onSurfaceVariant':'onSurfaceVariant','outline':'outline','outlineVariant':'outlineVariant','error':'error','onError':'surfaceContainer','errorContainer':'errorContainer','onErrorContainer':'error'}
dart=["// Generated from Odyssey 3 tokens; opt-in, does not replace Odyssey 2.","import 'package:flutter/material.dart';", "\nThemeData odyssey3Theme({String brand = 'Clarity', Brightness brightness = Brightness.light, bool arabic = false}) {", "  final dark = brightness == Brightness.dark;", "  final data = _themes[brand]!;", "  final c = dark ? data['dark']! : data['light']!;", "  Color color(String role) => Color(c[role] as int);", "  final scheme = ColorScheme.fromSeed(seedColor: color('primary'), brightness: brightness).copyWith("]
dart += [f"    {a}: color('{b}')," for a,b in roles.items() if a!='onError']
dart += ["    onError: dark ? const Color(0xFF492729) : Colors.white,", "    surfaceContainer: color('surfaceContainer'),", "    secondary: color('primary'), onSecondary: color('onPrimary'),", "    secondaryContainer: color('primaryContainer'), onSecondaryContainer: color('onPrimaryContainer'),", "  );", "  final radius = BorderRadius.circular(c['controlRadius'] as double);", "  final base = ThemeData(useMaterial3: true, colorScheme: scheme, scaffoldBackgroundColor: scheme.surface, fontFamily: arabic ? 'Beiruti' : 'Hanken Grotesk', visualDensity: VisualDensity.standard);", "  return base.copyWith(", "    textTheme: base.textTheme.copyWith(headlineLarge: base.textTheme.headlineLarge?.copyWith(fontFamily: arabic ? 'Beiruti' : c['displayFamily'] as String, fontSize: 40, height: 1.2), headlineSmall: base.textTheme.headlineSmall?.copyWith(fontFamily: arabic ? 'Beiruti' : c['displayFamily'] as String, fontSize: 28, height: 1.28), bodyLarge: base.textTheme.bodyLarge?.copyWith(fontSize: arabic ? 18 : 16, height: 1.5)),", "    filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(minimumSize: const Size(48, 56), shape: RoundedRectangleBorder(borderRadius: radius))),", "    outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(minimumSize: const Size(48, 56), shape: RoundedRectangleBorder(borderRadius: radius))),", "    inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: scheme.surfaceContainer, border: OutlineInputBorder(borderRadius: radius)),", "  );", "}", "\nconst _themes = <String, Map<String, Map<String, Object>>>{"]
for brand,modes in resolved.items():
    dart.append(f"  '{brand}': {{")
    for mode,v in modes.items():
        dart.append(f"    '{mode.lower()}': {{")
        dart += [f"      '{n.split('/')[1]}': 0xFF{val[1:]}," for n,val in v.items() if n.startswith('color/')]
        dart += [f"      'controlRadius': {v['brand/controlRadius']}.0,",f"      'displayFamily': '{v['brand/displayFamily']}',", "    },"]
    dart.append('  },')
dart.append('};')
(ROOT/'platforms').mkdir(exist_ok=True)
(ROOT/'platforms/odyssey3_theme.dart').write_text('\n'.join(dart)+'\n')
kt=['// Generated opt-in Material 3 colour/shape adapter. Supply bundled font families in the host.','package ly.neptune.odyssey.livingworlds','', 'import androidx.compose.material3.*','import androidx.compose.ui.graphics.Color','import androidx.compose.foundation.shape.RoundedCornerShape','import androidx.compose.ui.unit.dp','', 'fun odyssey3Colors(brand: String = "Clarity", dark: Boolean = false): ColorScheme = when (brand to dark) {']
for brand,modes in resolved.items():
    for mode,v in modes.items():
        dark=mode=='Dark';kt.append(f'    ("{brand}" to {str(dark).lower()}) -> '+('darkColorScheme(' if dark else 'lightColorScheme('))
        kt += [f'        {a} = Color(0xFF{v["color/"+b][1:]}),' for a,b in roles.items() if a!='onError']
        kt += [f'        onError = Color(0xFF{"492729" if dark else "FFFFFF"}),',f'        surfaceContainer = Color(0xFF{v["color/surfaceContainer"][1:]}),',f'        secondary = Color(0xFF{v["color/primary"][1:]}),',f'        onSecondary = Color(0xFF{v["color/onPrimary"][1:]}),',f'        secondaryContainer = Color(0xFF{v["color/primaryContainer"][1:]}),',f'        onSecondaryContainer = Color(0xFF{v["color/onPrimaryContainer"][1:]}),','    )']
kt += ['    else -> error("Unknown Odyssey identity: $brand")','}', '', 'fun odyssey3Shapes(brand: String) = Shapes(', '    small = RoundedCornerShape(4.dp),', '    medium = RoundedCornerShape((when (brand) { "Clarity" -> 12; "Reserve" -> 8; "Drive" -> 24; "Orbit" -> 20; else -> error("Unknown identity") }).dp),', '    large = RoundedCornerShape((when (brand) { "Clarity" -> 16; "Reserve" -> 12; "Drive" -> 28; "Orbit" -> 24; else -> error("Unknown identity") }).dp),', ')']
(ROOT/'platforms/Odyssey3Theme.kt').write_text(('\n'.join(kt)+'\n').replace('fun odyssey3Colors(', 'public fun odyssey3Colors(').replace('fun odyssey3Shapes(brand: String) =', 'public fun odyssey3Shapes(brand: String): Shapes ='))
assert len(resolved)==4 and all(len(m)==2 for m in resolved.values())
failures=[r for r in report if not r['pass']]
print(json.dumps({'tokens':len(tokens),'themes':8,'contrastPairs':len(report),'failures':failures},indent=2))
assert not failures, 'A required foreground/background pair fails contrast.'
