// GENERATED by packages/neptune_kmp_ui/tools/gen-icons.mjs — DO NOT EDIT.
// © 2026 Neptune.Fintech (neptune.ly) · Neptune Odyssey Community License v1.0
//
// The full Neptune Odyssey icon family, ported from
// packages/neptune_icons/src/icons.ts: 24×24 grid, stroke 1.8, round
// caps/joins, fill none. Non-path SVG elements (circle/ellipse/rect/…) are
// pre-converted to path data by the generator. The Color.White paints are
// templates — Icon()'s `tint` replaces them (the currentColor pattern).
//
// Regenerate: node packages/neptune_kmp_ui/tools/gen-icons.mjs

package ly.neptune.odyssey.ui.glyphs

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/** 24×24 icon canvas — mirrors the nptGlyph builder defaults. */
private fun nptIconBuilder(name: String): ImageVector.Builder = ImageVector.Builder(
    name = name,
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 24f,
    viewportHeight = 24f,
)

/** Outlined stroke path — the family default (stroke 1.8, round caps/joins). */
private fun ImageVector.Builder.strokePath(
    d: String,
    strokeWidth: Float = 1.8f,
): ImageVector.Builder = addPath(
    pathData = addPathNodes(d),
    stroke = SolidColor(Color.White),
    strokeLineWidth = strokeWidth,
    strokeLineCap = StrokeCap.Round,
    strokeLineJoin = StrokeJoin.Round,
    fill = null,
)

/** Filled path — source elements with fill="currentColor" stroke="none". */
private fun ImageVector.Builder.fillPath(d: String): ImageVector.Builder = addPath(
    pathData = addPathNodes(d),
    fill = SolidColor(Color.White),
    stroke = null,
)

/** The Neptune Odyssey icon family (tinted via Icon's `tint` / currentColor). */
public object NptIcons {
    /** `home` */
    public val home: ImageVector by lazy {
        nptIconBuilder("npt.home")
            .strokePath("M4 11 12 4l8 7")
            .strokePath("M6 10v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-9")
            .strokePath("M10 20v-5h4v5")
            .build()
    }

    /** `accounts` */
    public val accounts: ImageVector by lazy {
        nptIconBuilder("npt.accounts")
            .strokePath("M5.5 6h13a2.5 2.5 0 0 1 2.5 2.5v8a2.5 2.5 0 0 1 -2.5 2.5h-13a2.5 2.5 0 0 1 -2.5 -2.5v-8a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M3 10h18")
            .strokePath("M7 15h4")
            .build()
    }

    /** `card` */
    public val card: ImageVector by lazy {
        nptIconBuilder("npt.card")
            .strokePath("M5.5 5h13a2.5 2.5 0 0 1 2.5 2.5v9a2.5 2.5 0 0 1 -2.5 2.5h-13a2.5 2.5 0 0 1 -2.5 -2.5v-9a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M3 9.5h18")
            .strokePath("M6.5 14.5h4")
            .build()
    }

    /** `card-add` */
    public val cardAdd: ImageVector by lazy {
        nptIconBuilder("npt.cardAdd")
            .strokePath("M21 11V7.5A2.5 2.5 0 0 0 18.5 5h-13A2.5 2.5 0 0 0 3 7.5V16a2.5 2.5 0 0 0 2.5 2.5H12")
            .strokePath("M3 9.5h18")
            .strokePath("M18 15v6")
            .strokePath("M15 18h6")
            .build()
    }

    /** `wallet` */
    public val wallet: ImageVector by lazy {
        nptIconBuilder("npt.wallet")
            .strokePath("M4 7.5A2.5 2.5 0 0 1 6.5 5H17a1 1 0 0 1 1 1v1.5")
            .strokePath("M6.5 7.5h11a2.5 2.5 0 0 1 2.5 2.5v7a2.5 2.5 0 0 1 -2.5 2.5h-11a2.5 2.5 0 0 1 -2.5 -2.5v-7a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M16 13h2")
            .strokePath("M20 11.5h-3a1.5 1.5 0 0 0 0 3h3")
            .build()
    }

    /** `transfer` */
    public val transfer: ImageVector by lazy {
        nptIconBuilder("npt.transfer")
            .strokePath("M5 9h12l-3-3")
            .strokePath("M19 15H7l3 3")
            .build()
    }

    /** `send` */
    public val send: ImageVector by lazy {
        nptIconBuilder("npt.send")
            .strokePath("M20 4 9.5 14.5")
            .strokePath("M20 4 13.5 20l-4-7-7-4Z")
            .build()
    }

    /** `receive` */
    public val receive: ImageVector by lazy {
        nptIconBuilder("npt.receive")
            .strokePath("M12 4v11")
            .strokePath("M7.5 10.5 12 15l4.5-4.5")
            .strokePath("M5 19h14")
            .build()
    }

    /** `request` */
    public val request: ImageVector by lazy {
        nptIconBuilder("npt.request")
            .strokePath("M12 20V9")
            .strokePath("M16.5 13.5 12 9 7.5 13.5")
            .strokePath("M5 5h14")
            .build()
    }

    /** `swap-exchange` */
    public val swapExchange: ImageVector by lazy {
        nptIconBuilder("npt.swapExchange")
            .strokePath("M6 8h11l-3.5-3.5")
            .strokePath("M6 8V6")
            .strokePath("M18 16H7l3.5 3.5")
            .strokePath("M18 16v2")
            .build()
    }

    /** `qr-code` */
    public val qrCode: ImageVector by lazy {
        nptIconBuilder("npt.qrCode")
            .strokePath("M5.2 4h3.6a1.2 1.2 0 0 1 1.2 1.2v3.6a1.2 1.2 0 0 1 -1.2 1.2h-3.6a1.2 1.2 0 0 1 -1.2 -1.2v-3.6a1.2 1.2 0 0 1 1.2 -1.2Z")
            .strokePath("M15.2 4h3.6a1.2 1.2 0 0 1 1.2 1.2v3.6a1.2 1.2 0 0 1 -1.2 1.2h-3.6a1.2 1.2 0 0 1 -1.2 -1.2v-3.6a1.2 1.2 0 0 1 1.2 -1.2Z")
            .strokePath("M5.2 14h3.6a1.2 1.2 0 0 1 1.2 1.2v3.6a1.2 1.2 0 0 1 -1.2 1.2h-3.6a1.2 1.2 0 0 1 -1.2 -1.2v-3.6a1.2 1.2 0 0 1 1.2 -1.2Z")
            .strokePath("M14 14h2v2")
            .strokePath("M20 14v2")
            .strokePath("M14 20h6")
            .strokePath("M20 18v2")
            .build()
    }

    /** `contactless` */
    public val contactless: ImageVector by lazy {
        nptIconBuilder("npt.contactless")
            .strokePath("M7 8a8 8 0 0 1 0 8")
            .strokePath("M11 6a12 12 0 0 1 0 12")
            .strokePath("M15 4.5a16 16 0 0 1 0 15")
            .build()
    }

    /** `bill` */
    public val bill: ImageVector by lazy {
        nptIconBuilder("npt.bill")
            .strokePath("M6 3.5h9l3 3V20a.8.8 0 0 1-1.2.7L15 19.5l-1.5 1.2a1 1 0 0 1-1.2 0L10.8 19.5 9.3 20.7a1 1 0 0 1-1.2 0L6.6 19.5 5.2 20.7A.8.8 0 0 1 4 20V5.5A2 2 0 0 1 6 3.5Z")
            .strokePath("M8.5 9h7")
            .strokePath("M8.5 12.5h5")
            .build()
    }

    /** `receipt` */
    public val receipt: ImageVector by lazy {
        nptIconBuilder("npt.receipt")
            .strokePath("M6 3.5h12V20a.8.8 0 0 1-1.2.7L15 19.5l-1.5 1.2a1 1 0 0 1-1.2 0L10.8 19.5 9.3 20.7a1 1 0 0 1-1.2 0L6.6 19.5 5.2 20.7A.8.8 0 0 1 6 20Z")
            .strokePath("M9 8h6")
            .strokePath("M9 11.5h6")
            .strokePath("M9 15h3")
            .build()
    }

    /** `statement` */
    public val statement: ImageVector by lazy {
        nptIconBuilder("npt.statement")
            .strokePath("M7 3.5h10a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-13a2 2 0 0 1 2 -2Z")
            .strokePath("M8.5 8h7")
            .strokePath("M8.5 11.5h7")
            .strokePath("M8.5 15h4")
            .build()
    }

    /** `pdf` */
    public val pdf: ImageVector by lazy {
        nptIconBuilder("npt.pdf")
            .strokePath("M7 3.5h7l4 4V19a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 6 19V5A1.5 1.5 0 0 1 7.5 3.5Z")
            .strokePath("M14 3.5V8h4")
            .strokePath("M9 16.5v-4h1.2a1.2 1.2 0 0 1 0 2.4H9")
            .strokePath("M14 12.5v4")
            .strokePath("M14 12.5h1.6")
            .strokePath("M14 14.5h1.2")
            .build()
    }

    /** `download` */
    public val download: ImageVector by lazy {
        nptIconBuilder("npt.download")
            .strokePath("M12 4v10")
            .strokePath("M7.5 9.5 12 14l4.5-4.5")
            .strokePath("M5 18.5h14")
            .build()
    }

    /** `upload` */
    public val upload: ImageVector by lazy {
        nptIconBuilder("npt.upload")
            .strokePath("M12 14V4")
            .strokePath("M7.5 8.5 12 4l4.5 4.5")
            .strokePath("M5 18.5h14")
            .build()
    }

    /** `search` */
    public val search: ImageVector by lazy {
        nptIconBuilder("npt.search")
            .strokePath("M4.5 11a6.5 6.5 0 1 0 13 0a6.5 6.5 0 1 0 -13 0")
            .strokePath("M16 16l3.5 3.5")
            .build()
    }

    /** `filter` */
    public val filter: ImageVector by lazy {
        nptIconBuilder("npt.filter")
            .strokePath("M4 6h16")
            .strokePath("M7 11h10")
            .strokePath("M10 16h4")
            .build()
    }

    /** `settings` */
    public val settings: ImageVector by lazy {
        nptIconBuilder("npt.settings")
            .strokePath("M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")
            .strokePath("M12 3v2.2")
            .strokePath("M12 18.8V21")
            .strokePath("M3 12h2.2")
            .strokePath("M18.8 12H21")
            .strokePath("m5.6 5.6 1.6 1.6")
            .strokePath("m16.8 16.8 1.6 1.6")
            .strokePath("m18.4 5.6-1.6 1.6")
            .strokePath("m7.2 16.8-1.6 1.6")
            .build()
    }

    /** `user` */
    public val user: ImageVector by lazy {
        nptIconBuilder("npt.user")
            .strokePath("M8.5 8a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0")
            .strokePath("M5.5 19.5a6.5 6.5 0 0 1 13 0")
            .build()
    }

    /** `users` */
    public val users: ImageVector by lazy {
        nptIconBuilder("npt.users")
            .strokePath("M6 8a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")
            .strokePath("M3.5 19a5.5 5.5 0 0 1 11 0")
            .strokePath("M16 5.2a3 3 0 0 1 0 5.6")
            .strokePath("M17 14.2a5.5 5.5 0 0 1 3.5 4.8")
            .build()
    }

    /** `security-shield` */
    public val securityShield: ImageVector by lazy {
        nptIconBuilder("npt.securityShield")
            .strokePath("M12 3.5 19 6v5.5c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6Z")
            .strokePath("m9 12 2 2 4-4")
            .build()
    }

    /** `lock` */
    public val lock: ImageVector by lazy {
        nptIconBuilder("npt.lock")
            .strokePath("M7 10.5h10a2 2 0 0 1 2 2v5a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-5a2 2 0 0 1 2 -2Z")
            .strokePath("M8 10.5V8a4 4 0 0 1 8 0v2.5")
            .fillPath("M10.9 15a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .build()
    }

    /** `unlock` */
    public val unlock: ImageVector by lazy {
        nptIconBuilder("npt.unlock")
            .strokePath("M7 10.5h10a2 2 0 0 1 2 2v5a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-5a2 2 0 0 1 2 -2Z")
            .strokePath("M8 10.5V8a4 4 0 0 1 7.5-1.9")
            .fillPath("M10.9 15a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .build()
    }

    /** `key` */
    public val key: ImageVector by lazy {
        nptIconBuilder("npt.key")
            .strokePath("M4 8a4 4 0 1 0 8 0a4 4 0 1 0 -8 0")
            .strokePath("m11 11 8 8")
            .strokePath("m16.5 16.5 1.8-1.8")
            .strokePath("m18.5 18.5 1.8-1.8")
            .build()
    }

    /** `fingerprint` */
    public val fingerprint: ImageVector by lazy {
        nptIconBuilder("npt.fingerprint")
            .strokePath("M7 11a5 5 0 0 1 10 0v1")
            .strokePath("M9.5 11a2.5 2.5 0 0 1 5 0v1.5a6 6 0 0 0 .8 3")
            .strokePath("M12 11v3a8 8 0 0 0 1.2 4.2")
            .strokePath("M9.5 14a8 8 0 0 0 1 4.5")
            .strokePath("M5 13a9 9 0 0 1 1.2-7")
            .strokePath("M18.8 6.5A9 9 0 0 1 19 13")
            .build()
    }

    /** `face-id` */
    public val faceId: ImageVector by lazy {
        nptIconBuilder("npt.faceId")
            .strokePath("M4 8V6.5A2.5 2.5 0 0 1 6.5 4H8")
            .strokePath("M16 4h1.5A2.5 2.5 0 0 1 20 6.5V8")
            .strokePath("M20 16v1.5a2.5 2.5 0 0 1-2.5 2.5H16")
            .strokePath("M8 20H6.5A2.5 2.5 0 0 1 4 17.5V16")
            .strokePath("M9.5 9.5v1")
            .strokePath("M14.5 9.5v1")
            .strokePath("M12 9.5v3l-1 .8")
            .strokePath("M9.5 15a3.5 3.5 0 0 0 5 0")
            .build()
    }

    /** `id-card` */
    public val idCard: ImageVector by lazy {
        nptIconBuilder("npt.idCard")
            .strokePath("M5.5 5h13a2.5 2.5 0 0 1 2.5 2.5v9a2.5 2.5 0 0 1 -2.5 2.5h-13a2.5 2.5 0 0 1 -2.5 -2.5v-9a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M6.4 11a2.1 2.1 0 1 0 4.2 0a2.1 2.1 0 1 0 -4.2 0")
            .strokePath("M5.5 15.8c0-1.7 1.3-3 3-3s3 1.3 3 3")
            .strokePath("M14 9.5h5")
            .strokePath("M14 13h5")
            .build()
    }

    /** `otp` */
    public val otp: ImageVector by lazy {
        nptIconBuilder("npt.otp")
            .strokePath("M5 8h14a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-4a2 2 0 0 1 2 -2Z")
            .fillPath("M5.9 12a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .fillPath("M9.9 12a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .fillPath("M13.9 12a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .fillPath("M17.9 12a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .build()
    }

    /** `bell` */
    public val bell: ImageVector by lazy {
        nptIconBuilder("npt.bell")
            .strokePath("M6 16.5V11a6 6 0 0 1 12 0v5.5l1.5 2H4.5Z")
            .strokePath("M10 18.5a2 2 0 0 0 4 0")
            .build()
    }

    /** `eye` */
    public val eye: ImageVector by lazy {
        nptIconBuilder("npt.eye")
            .strokePath("M3 12c2.2-4 5.5-6 9-6s6.8 2 9 6c-2.2 4-5.5 6-9 6s-6.8-2-9-6Z")
            .strokePath("M9.4 12a2.6 2.6 0 1 0 5.2 0a2.6 2.6 0 1 0 -5.2 0")
            .build()
    }

    /** `eye-off` */
    public val eyeOff: ImageVector by lazy {
        nptIconBuilder("npt.eyeOff")
            .strokePath("M4 4 20 20")
            .strokePath("M9.6 9.7A2.6 2.6 0 0 0 12 14.6")
            .strokePath("M7 7.3C5.3 8.4 3.9 10 3 12c2.2 4 5.5 6 9 6 1.5 0 2.9-.3 4.2-1")
            .strokePath("M14.7 9.5A2.6 2.6 0 0 0 12 9.4")
            .strokePath("M17.4 7.6c1.3 1 2.5 2.5 3.6 4.4-1 1.7-2.1 3-3.5 4")
            .build()
    }

    /** `info` */
    public val info: ImageVector by lazy {
        nptIconBuilder("npt.info")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 11v5")
            .fillPath("M10.9 8a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0")
            .build()
    }

    /** `success-check` */
    public val successCheck: ImageVector by lazy {
        nptIconBuilder("npt.successCheck")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("m8.5 12 2.3 2.3 4.7-4.6")
            .build()
    }

    /** `warning` */
    public val warning: ImageVector by lazy {
        nptIconBuilder("npt.warning")
            .strokePath("M12 4.5 21 19.5H3Z")
            .strokePath("M12 10v4")
            .fillPath("M11 17a1 1 0 1 0 2 0a1 1 0 1 0 -2 0")
            .build()
    }

    /** `error` */
    public val error: ImageVector by lazy {
        nptIconBuilder("npt.error")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 8v5")
            .fillPath("M11 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0")
            .build()
    }

    /** `close` */
    public val close: ImageVector by lazy {
        nptIconBuilder("npt.close")
            .strokePath("M6 6 18 18")
            .strokePath("M18 6 6 18")
            .build()
    }

    /** `plus` */
    public val plus: ImageVector by lazy {
        nptIconBuilder("npt.plus")
            .strokePath("M12 5v14")
            .strokePath("M5 12h14")
            .build()
    }

    /** `minus` */
    public val minus: ImageVector by lazy {
        nptIconBuilder("npt.minus")
            .strokePath("M5 12h14")
            .build()
    }

    /** `star` */
    public val star: ImageVector by lazy {
        nptIconBuilder("npt.star")
            .strokePath("M12 3.5l2.6 5.9 6.4.6-4.8 4.3 1.4 6.3L12 17.6l-5.6 3 1.4-6.3-4.8-4.3 6.4-.6L12 3.5Z")
            .build()
    }

    /** `chart-line` */
    public val chartLine: ImageVector by lazy {
        nptIconBuilder("npt.chartLine")
            .strokePath("M4 4v15a1 1 0 0 0 1 1h15")
            .strokePath("M7 15l3.5-4 3 2.5L20 7")
            .build()
    }

    /** `chart-pie` */
    public val chartPie: ImageVector by lazy {
        nptIconBuilder("npt.chartPie")
            .strokePath("M12 4a8 8 0 1 0 8 8h-8Z")
            .strokePath("M14 3.2A8 8 0 0 1 20.8 10H14Z")
            .build()
    }

    /** `trending-up` */
    public val trendingUp: ImageVector by lazy {
        nptIconBuilder("npt.trendingUp")
            .strokePath("M4 16l5-5 3 3 7-7")
            .strokePath("M15 7h4v4")
            .build()
    }

    /** `trending-down` */
    public val trendingDown: ImageVector by lazy {
        nptIconBuilder("npt.trendingDown")
            .strokePath("M4 8l5 5 3-3 7 7")
            .strokePath("M15 17h4v-4")
            .build()
    }

    /** `savings` */
    public val savings: ImageVector by lazy {
        nptIconBuilder("npt.savings")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 6.5v11")
            .strokePath("M14.5 8.5h-3.2a2 2 0 0 0 0 4h2.4a2 2 0 0 1 0 4H10")
            .build()
    }

    /** `calendar` */
    public val calendar: ImageVector by lazy {
        nptIconBuilder("npt.calendar")
            .strokePath("M6.5 5.5h11a2.5 2.5 0 0 1 2.5 2.5v9.5a2.5 2.5 0 0 1 -2.5 2.5h-11a2.5 2.5 0 0 1 -2.5 -2.5v-9.5a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M4 10h16")
            .strokePath("M8 3.5v3.5")
            .strokePath("M16 3.5v3.5")
            .build()
    }

    /** `clock` */
    public val clock: ImageVector by lazy {
        nptIconBuilder("npt.clock")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 7.5V12l3 2")
            .build()
    }

    /** `location` */
    public val location: ImageVector by lazy {
        nptIconBuilder("npt.location")
            .strokePath("M12 21c-3.5-3.4-6-6.4-6-9.5a6 6 0 0 1 12 0c0 3.1-2.5 6.1-6 9.5Z")
            .strokePath("M9.6 11a2.4 2.4 0 1 0 4.8 0a2.4 2.4 0 1 0 -4.8 0")
            .build()
    }

    /** `phone` */
    public val phone: ImageVector by lazy {
        nptIconBuilder("npt.phone")
            .strokePath("M6 4h3l1.5 4-2 1.5a11 11 0 0 0 5 5l1.5-2 4 1.5V19a2 2 0 0 1-2.2 2A15.5 15.5 0 0 1 5 8.2 2 2 0 0 1 6 4Z")
            .build()
    }

    /** `mail` */
    public val mail: ImageVector by lazy {
        nptIconBuilder("npt.mail")
            .strokePath("M6 6h12a2.5 2.5 0 0 1 2.5 2.5v7a2.5 2.5 0 0 1 -2.5 2.5h-12a2.5 2.5 0 0 1 -2.5 -2.5v-7a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("m4.5 8 7.5 5.5L19.5 8")
            .build()
    }

    /** `chat` */
    public val chat: ImageVector by lazy {
        nptIconBuilder("npt.chat")
            .strokePath("M4.5 6A2.5 2.5 0 0 1 7 3.5h10A2.5 2.5 0 0 1 19.5 6v7A2.5 2.5 0 0 1 17 15.5H9l-4.5 4Z")
            .build()
    }

    /** `camera` */
    public val camera: ImageVector by lazy {
        nptIconBuilder("npt.camera")
            .strokePath("M4 8.5A1.5 1.5 0 0 1 5.5 7h2l1-2h7l1 2h2A1.5 1.5 0 0 1 20 8.5V18a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18Z")
            .strokePath("M8.8 13a3.2 3.2 0 1 0 6.4 0a3.2 3.2 0 1 0 -6.4 0")
            .build()
    }

    /** `globe` */
    public val globe: ImageVector by lazy {
        nptIconBuilder("npt.globe")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M3.5 12h17")
            .strokePath("M12 3.5c2.4 2.3 3.7 5.3 3.7 8.5s-1.3 6.2-3.7 8.5c-2.4-2.3-3.7-5.3-3.7-8.5S9.6 5.8 12 3.5Z")
            .build()
    }

    /** `support` */
    public val support: ImageVector by lazy {
        nptIconBuilder("npt.support")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M9.5 10a2.5 2.5 0 0 1 4.6 1.3c0 1.7-2.1 1.9-2.1 3.2")
            .fillPath("M11 17a1 1 0 1 0 2 0a1 1 0 1 0 -2 0")
            .build()
    }

    /** `chevron-right` */
    public val chevronRight: ImageVector by lazy {
        nptIconBuilder("npt.chevronRight")
            .strokePath("M9.5 5.5 16 12l-6.5 6.5")
            .build()
    }

    /** `chevron-down` */
    public val chevronDown: ImageVector by lazy {
        nptIconBuilder("npt.chevronDown")
            .strokePath("M5.5 9.5 12 16l6.5-6.5")
            .build()
    }

    /** `chevron-up` */
    public val chevronUp: ImageVector by lazy {
        nptIconBuilder("npt.chevronUp")
            .strokePath("M5.5 14.5 12 8l6.5 6.5")
            .build()
    }

    /** `chevron-left` */
    public val chevronLeft: ImageVector by lazy {
        nptIconBuilder("npt.chevronLeft")
            .strokePath("M14.5 5.5 8 12l6.5 6.5")
            .build()
    }

    /** `arrow-right` */
    public val arrowRight: ImageVector by lazy {
        nptIconBuilder("npt.arrowRight")
            .strokePath("M4 12h15")
            .strokePath("m13 6 6 6-6 6")
            .build()
    }

    /** `arrow-left` */
    public val arrowLeft: ImageVector by lazy {
        nptIconBuilder("npt.arrowLeft")
            .strokePath("M20 12H5")
            .strokePath("m11 6-6 6 6 6")
            .build()
    }

    /** `arrow-up` */
    public val arrowUp: ImageVector by lazy {
        nptIconBuilder("npt.arrowUp")
            .strokePath("M12 20V5")
            .strokePath("m6 11 6-6 6 6")
            .build()
    }

    /** `arrow-down` */
    public val arrowDown: ImageVector by lazy {
        nptIconBuilder("npt.arrowDown")
            .strokePath("M12 4v15")
            .strokePath("m18 13-6 6-6-6")
            .build()
    }

    /** `menu` */
    public val menu: ImageVector by lazy {
        nptIconBuilder("npt.menu")
            .strokePath("M4 7h16")
            .strokePath("M4 12h16")
            .strokePath("M4 17h16")
            .build()
    }

    /** `more-horizontal` */
    public val moreHorizontal: ImageVector by lazy {
        nptIconBuilder("npt.moreHorizontal")
            .fillPath("M4.2 12a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .fillPath("M10.7 12a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .fillPath("M17.2 12a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .build()
    }

    /** `more-vertical` */
    public val moreVertical: ImageVector by lazy {
        nptIconBuilder("npt.moreVertical")
            .fillPath("M10.7 5.5a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .fillPath("M10.7 12a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .fillPath("M10.7 18.5a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0")
            .build()
    }

    /** `copy` */
    public val copy: ImageVector by lazy {
        nptIconBuilder("npt.copy")
            .strokePath("M10.5 8h7a2.5 2.5 0 0 1 2.5 2.5v7a2.5 2.5 0 0 1 -2.5 2.5h-7a2.5 2.5 0 0 1 -2.5 -2.5v-7a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2")
            .build()
    }

    /** `share` */
    public val share: ImageVector by lazy {
        nptIconBuilder("npt.share")
            .strokePath("M4.5 12a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0")
            .strokePath("M14.5 6a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0")
            .strokePath("M14.5 18a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0")
            .strokePath("m9.2 10.8 5.6-3.4")
            .strokePath("m9.2 13.2 5.6 3.4")
            .build()
    }

    /** `logout` */
    public val logout: ImageVector by lazy {
        nptIconBuilder("npt.logout")
            .strokePath("M14 4.5H6.5A1.5 1.5 0 0 0 5 6v12a1.5 1.5 0 0 0 1.5 1.5H14")
            .strokePath("M11 12h9")
            .strokePath("m16.5 8 3.5 4-3.5 4")
            .build()
    }

    /** `language` */
    public val language: ImageVector by lazy {
        nptIconBuilder("npt.language")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M3.5 12h17")
            .strokePath("M12 3.5c2.4 2.3 3.7 5.3 3.7 8.5S14.4 18.2 12 20.5c-2.4-2.3-3.7-5.3-3.7-8.5S9.6 5.8 12 3.5Z")
            .build()
    }

    /** `moon` */
    public val moon: ImageVector by lazy {
        nptIconBuilder("npt.moon")
            .strokePath("M20 13.5A8 8 0 0 1 10.5 4 8 8 0 1 0 20 13.5Z")
            .build()
    }

    /** `sun` */
    public val sun: ImageVector by lazy {
        nptIconBuilder("npt.sun")
            .strokePath("M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0")
            .strokePath("M12 3v2.2")
            .strokePath("M12 18.8V21")
            .strokePath("M3 12h2.2")
            .strokePath("M18.8 12H21")
            .strokePath("m5.4 5.4 1.6 1.6")
            .strokePath("m17 17 1.6 1.6")
            .strokePath("m18.6 5.4-1.6 1.6")
            .strokePath("m7 17-1.6 1.6")
            .build()
    }

    /** `atm` */
    public val atm: ImageVector by lazy {
        nptIconBuilder("npt.atm")
            .strokePath("M6 4.5h12a2 2 0 0 1 2 2v11a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2Z")
            .strokePath("M4 9h16")
            .strokePath("M7.5 13h3")
            .strokePath("M7.5 16h6")
            .strokePath("M16 13.5v3")
            .build()
    }

    /** `pos-terminal` */
    public val posTerminal: ImageVector by lazy {
        nptIconBuilder("npt.posTerminal")
            .strokePath("M8 3.5h8a2 2 0 0 1 2 2v13a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-13a2 2 0 0 1 2 -2Z")
            .strokePath("M6 8h12")
            .strokePath("M9 5.5h6")
            .strokePath("M9 12h2")
            .strokePath("M13 12h2")
            .strokePath("M9 15.5h2")
            .strokePath("M13 15.5h2")
            .build()
    }

    /** `coins` */
    public val coins: ImageVector by lazy {
        nptIconBuilder("npt.coins")
            .strokePath("M4 7a5 2.5 0 1 0 10 0a5 2.5 0 1 0 -10 0")
            .strokePath("M4 7v4c0 1.4 2.2 2.5 5 2.5s5-1.1 5-2.5V7")
            .strokePath("M10 15a5 2.5 0 1 0 10 0a5 2.5 0 1 0 -10 0")
            .strokePath("M10 15v4c0 1.4 2.2 2.5 5 2.5s5-1.1 5-2.5v-4")
            .build()
    }

    /** `cash-stack` */
    public val cashStack: ImageVector by lazy {
        nptIconBuilder("npt.cashStack")
            .strokePath("M5 7h14a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-7a2 2 0 0 1 2 -2Z")
            .strokePath("M9.6 12.5a2.4 2.4 0 1 0 4.8 0a2.4 2.4 0 1 0 -4.8 0")
            .strokePath("M3 11h2")
            .strokePath("M19 11h2")
            .strokePath("M5 5h14")
            .build()
    }

    /** `invoice` */
    public val invoice: ImageVector by lazy {
        nptIconBuilder("npt.invoice")
            .strokePath("M6 3.5h9l3 3V20a.8.8 0 0 1-1.2.7L15 19.5l-1.5 1.2a1 1 0 0 1-1.2 0L10.8 19.5 9.3 20.7a1 1 0 0 1-1.2 0L6.6 19.5 5.2 20.7A.8.8 0 0 1 4 20V5.5A2 2 0 0 1 6 3.5Z")
            .strokePath("M12 8.5v6")
            .strokePath("M13.8 10h-2.6a1.4 1.4 0 0 0 0 2.8h1.6a1.4 1.4 0 0 1 0 2.8H10")
            .build()
    }

    /** `pie-budget` */
    public val pieBudget: ImageVector by lazy {
        nptIconBuilder("npt.pieBudget")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 12V3.5")
            .strokePath("M12 12l6 6")
            .build()
    }

    /** `exchange-rate` */
    public val exchangeRate: ImageVector by lazy {
        nptIconBuilder("npt.exchangeRate")
            .strokePath("M4 8h10l-3-3")
            .strokePath("M4 8V6")
            .strokePath("M20 16H10l3 3")
            .strokePath("M20 16v2")
            .strokePath("M6.2 13h1.6")
            .strokePath("M7 12.2v1.6")
            .strokePath("M16.2 11h1.6")
            .build()
    }

    /** `crypto` */
    public val crypto: ImageVector by lazy {
        nptIconBuilder("npt.crypto")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M9.5 8h4a2.2 2.2 0 0 1 0 4.4h-4")
            .strokePath("M9.5 12.4h4.3a2.2 2.2 0 0 1 0 4.4H9.5")
            .strokePath("M9.5 8v8.8")
            .strokePath("M11 6.5v1.5")
            .strokePath("M11 16.8v1.5")
            .strokePath("M13 6.5v1.5")
            .strokePath("M13 16.8v1.5")
            .build()
    }

    /** `loan` */
    public val loan: ImageVector by lazy {
        nptIconBuilder("npt.loan")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M12 6.5v11")
            .strokePath("M14.5 8.5h-3.2a2 2 0 0 0 0 4h2.4a2 2 0 0 1 0 4H10")
            .strokePath("m17 5 3 3-3 3")
            .strokePath("M20 8h-6")
            .build()
    }

    /** `insurance` */
    public val insurance: ImageVector by lazy {
        nptIconBuilder("npt.insurance")
            .strokePath("M12 3.5 19 6v5.5c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6Z")
            .strokePath("M12 8.5v7")
            .strokePath("M8.5 12h7")
            .build()
    }

    /** `split-bill` */
    public val splitBill: ImageVector by lazy {
        nptIconBuilder("npt.splitBill")
            .strokePath("M5 8a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")
            .strokePath("M13 8a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")
            .strokePath("M3.5 19a4.5 4.5 0 0 1 9 0")
            .strokePath("M11.5 19a4.5 4.5 0 0 1 9 0")
            .build()
    }

    /** `tap-to-pay` */
    public val tapToPay: ImageVector by lazy {
        nptIconBuilder("npt.tapToPay")
            .strokePath("M5.5 6h8a2.5 2.5 0 0 1 2.5 2.5v7a2.5 2.5 0 0 1 -2.5 2.5h-8a2.5 2.5 0 0 1 -2.5 -2.5v-7a2.5 2.5 0 0 1 2.5 -2.5Z")
            .strokePath("M3 10h13")
            .strokePath("M6.5 14.5h3")
            .strokePath("M19 8.5a6 6 0 0 1 0 7")
            .strokePath("M21.5 6.5a9 9 0 0 1 0 11")
            .build()
    }

    /** `dispute` */
    public val dispute: ImageVector by lazy {
        nptIconBuilder("npt.dispute")
            .strokePath("M6 21V4")
            .strokePath("M6 4.5h11.5l-2.7 3.5 2.7 3.5H6")
            .build()
    }

    /** `refund` */
    public val refund: ImageVector by lazy {
        nptIconBuilder("npt.refund")
            .strokePath("M7.5 6.5 4 10l3.5 3.5")
            .strokePath("M4 10h9a6.5 6.5 0 0 1 6.5 6.5v1")
            .build()
    }

    /** `goal` */
    public val goal: ImageVector by lazy {
        nptIconBuilder("npt.goal")
            .strokePath("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0")
            .strokePath("M7 12a5 5 0 1 0 10 0a5 5 0 1 0 -10 0")
            .fillPath("M10.5 12a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0")
            .build()
    }

    /** `shopping-bag` */
    public val shoppingBag: ImageVector by lazy {
        nptIconBuilder("npt.shoppingBag")
            .strokePath("M6.5 8h11l1 12a1.5 1.5 0 0 1-1.5 1.6H7a1.5 1.5 0 0 1-1.5-1.6Z")
            .strokePath("M9 8V6.5a3 3 0 0 1 6 0V8")
            .build()
    }

    /** `category-tag` */
    public val categoryTag: ImageVector by lazy {
        nptIconBuilder("npt.categoryTag")
            .strokePath("M11.5 4h5A1.5 1.5 0 0 1 18 5.5v5a1.5 1.5 0 0 1-.44 1.06l-7 7a1.5 1.5 0 0 1-2.12 0l-5-5a1.5 1.5 0 0 1 0-2.12l7-7A1.5 1.5 0 0 1 11.5 4Z")
            .fillPath("M12.8 8a1.2 1.2 0 1 0 2.4 0a1.2 1.2 0 1 0 -2.4 0")
            .build()
    }

    /** `edit` */
    public val edit: ImageVector by lazy {
        nptIconBuilder("npt.edit")
            .strokePath("M4 20 5 15.5 15.5 5 19 8.5 8.5 19 4 20Z")
            .strokePath("M13 7 17 11")
            .build()
    }

    /** `trash` */
    public val trash: ImageVector by lazy {
        nptIconBuilder("npt.trash")
            .strokePath("M5 7h14")
            .strokePath("M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2")
            .strokePath("M6.5 7 7.3 19a1.5 1.5 0 0 0 1.5 1.4h6.4a1.5 1.5 0 0 0 1.5-1.4L17.5 7")
            .strokePath("M10 11v6")
            .strokePath("M14 11v6")
            .build()
    }

    /** `refresh` */
    public val refresh: ImageVector by lazy {
        nptIconBuilder("npt.refresh")
            .strokePath("M4.5 12a7.5 7.5 0 0 1 13.2-4.8")
            .strokePath("M19.5 3.5v4.5H15")
            .strokePath("M19.5 12a7.5 7.5 0 0 1-13.2 4.8")
            .strokePath("M4.5 20.5V16H9")
            .build()
    }

    /** `link` */
    public val link: ImageVector by lazy {
        nptIconBuilder("npt.link")
            .strokePath("M9.5 14.5 14.5 9.5")
            .strokePath("M8 16.5 5.5 14a3.5 3.5 0 0 1 0-5l1.5-1.5a3.5 3.5 0 0 1 5 0")
            .strokePath("M16 7.5 18.5 10a3.5 3.5 0 0 1 0 5L17 16.5a3.5 3.5 0 0 1-5 0")
            .build()
    }
}

/** Every icon name (kebab-case), in catalogue order — mirrors ICON_NAMES. */
public val nptIconNames: List<String> = listOf(
    "home", "accounts", "card", "card-add", "wallet", "transfer",
    "send", "receive", "request", "swap-exchange", "qr-code", "contactless",
    "bill", "receipt", "statement", "pdf", "download", "upload",
    "search", "filter", "settings", "user", "users", "security-shield",
    "lock", "unlock", "key", "fingerprint", "face-id", "id-card",
    "otp", "bell", "eye", "eye-off", "info", "success-check",
    "warning", "error", "close", "plus", "minus", "star",
    "chart-line", "chart-pie", "trending-up", "trending-down", "savings", "calendar",
    "clock", "location", "phone", "mail", "chat", "camera",
    "globe", "support", "chevron-right", "chevron-down", "chevron-up", "chevron-left",
    "arrow-right", "arrow-left", "arrow-up", "arrow-down", "menu", "more-horizontal",
    "more-vertical", "copy", "share", "logout", "language", "moon",
    "sun", "atm", "pos-terminal", "coins", "cash-stack", "invoice",
    "pie-budget", "exchange-rate", "crypto", "loan", "insurance", "split-bill",
    "tap-to-pay", "dispute", "refund", "goal", "shopping-bag", "category-tag",
    "edit", "trash", "refresh", "link",
)

private val nptIconLookup: Map<String, ImageVector> by lazy {
    mapOf(
        "home" to NptIcons.home,
        "accounts" to NptIcons.accounts,
        "card" to NptIcons.card,
        "card-add" to NptIcons.cardAdd,
        "wallet" to NptIcons.wallet,
        "transfer" to NptIcons.transfer,
        "send" to NptIcons.send,
        "receive" to NptIcons.receive,
        "request" to NptIcons.request,
        "swap-exchange" to NptIcons.swapExchange,
        "qr-code" to NptIcons.qrCode,
        "contactless" to NptIcons.contactless,
        "bill" to NptIcons.bill,
        "receipt" to NptIcons.receipt,
        "statement" to NptIcons.statement,
        "pdf" to NptIcons.pdf,
        "download" to NptIcons.download,
        "upload" to NptIcons.upload,
        "search" to NptIcons.search,
        "filter" to NptIcons.filter,
        "settings" to NptIcons.settings,
        "user" to NptIcons.user,
        "users" to NptIcons.users,
        "security-shield" to NptIcons.securityShield,
        "lock" to NptIcons.lock,
        "unlock" to NptIcons.unlock,
        "key" to NptIcons.key,
        "fingerprint" to NptIcons.fingerprint,
        "face-id" to NptIcons.faceId,
        "id-card" to NptIcons.idCard,
        "otp" to NptIcons.otp,
        "bell" to NptIcons.bell,
        "eye" to NptIcons.eye,
        "eye-off" to NptIcons.eyeOff,
        "info" to NptIcons.info,
        "success-check" to NptIcons.successCheck,
        "warning" to NptIcons.warning,
        "error" to NptIcons.error,
        "close" to NptIcons.close,
        "plus" to NptIcons.plus,
        "minus" to NptIcons.minus,
        "star" to NptIcons.star,
        "chart-line" to NptIcons.chartLine,
        "chart-pie" to NptIcons.chartPie,
        "trending-up" to NptIcons.trendingUp,
        "trending-down" to NptIcons.trendingDown,
        "savings" to NptIcons.savings,
        "calendar" to NptIcons.calendar,
        "clock" to NptIcons.clock,
        "location" to NptIcons.location,
        "phone" to NptIcons.phone,
        "mail" to NptIcons.mail,
        "chat" to NptIcons.chat,
        "camera" to NptIcons.camera,
        "globe" to NptIcons.globe,
        "support" to NptIcons.support,
        "chevron-right" to NptIcons.chevronRight,
        "chevron-down" to NptIcons.chevronDown,
        "chevron-up" to NptIcons.chevronUp,
        "chevron-left" to NptIcons.chevronLeft,
        "arrow-right" to NptIcons.arrowRight,
        "arrow-left" to NptIcons.arrowLeft,
        "arrow-up" to NptIcons.arrowUp,
        "arrow-down" to NptIcons.arrowDown,
        "menu" to NptIcons.menu,
        "more-horizontal" to NptIcons.moreHorizontal,
        "more-vertical" to NptIcons.moreVertical,
        "copy" to NptIcons.copy,
        "share" to NptIcons.share,
        "logout" to NptIcons.logout,
        "language" to NptIcons.language,
        "moon" to NptIcons.moon,
        "sun" to NptIcons.sun,
        "atm" to NptIcons.atm,
        "pos-terminal" to NptIcons.posTerminal,
        "coins" to NptIcons.coins,
        "cash-stack" to NptIcons.cashStack,
        "invoice" to NptIcons.invoice,
        "pie-budget" to NptIcons.pieBudget,
        "exchange-rate" to NptIcons.exchangeRate,
        "crypto" to NptIcons.crypto,
        "loan" to NptIcons.loan,
        "insurance" to NptIcons.insurance,
        "split-bill" to NptIcons.splitBill,
        "tap-to-pay" to NptIcons.tapToPay,
        "dispute" to NptIcons.dispute,
        "refund" to NptIcons.refund,
        "goal" to NptIcons.goal,
        "shopping-bag" to NptIcons.shoppingBag,
        "category-tag" to NptIcons.categoryTag,
        "edit" to NptIcons.edit,
        "trash" to NptIcons.trash,
        "refresh" to NptIcons.refresh,
        "link" to NptIcons.link,
    )
}

/** Look up an icon by its kebab-case neptune_icons name, or null if unknown. */
public fun nptIcon(name: String): ImageVector? = nptIconLookup[name]
