// Generated from Odyssey 3 tokens; opt-in, does not replace Odyssey 2.
import 'package:flutter/material.dart';

ThemeData odyssey3Theme({String brand = 'Clarity', Brightness brightness = Brightness.light, bool arabic = false}) {
  final dark = brightness == Brightness.dark;
  final data = _themes[brand]!;
  final c = dark ? data['dark']! : data['light']!;
  Color color(String role) => Color(c[role] as int);
  final scheme = ColorScheme.fromSeed(seedColor: color('primary'), brightness: brightness).copyWith(
    primary: color('primary'),
    onPrimary: color('onPrimary'),
    primaryContainer: color('primaryContainer'),
    onPrimaryContainer: color('onPrimaryContainer'),
    surface: color('surface'),
    onSurface: color('onSurface'),
    onSurfaceVariant: color('onSurfaceVariant'),
    outline: color('outline'),
    outlineVariant: color('outlineVariant'),
    error: color('error'),
    errorContainer: color('errorContainer'),
    onErrorContainer: color('error'),
    onError: dark ? const Color(0xFF492729) : Colors.white,
    surfaceContainer: color('surfaceContainer'),
    secondary: color('primary'), onSecondary: color('onPrimary'),
    secondaryContainer: color('primaryContainer'), onSecondaryContainer: color('onPrimaryContainer'),
  );
  final radius = BorderRadius.circular(c['controlRadius'] as double);
  final base = ThemeData(useMaterial3: true, colorScheme: scheme, scaffoldBackgroundColor: scheme.surface, fontFamily: arabic ? 'Beiruti' : 'Hanken Grotesk', visualDensity: VisualDensity.standard);
  return base.copyWith(
    textTheme: base.textTheme.copyWith(headlineLarge: base.textTheme.headlineLarge?.copyWith(fontFamily: arabic ? 'Beiruti' : c['displayFamily'] as String, fontSize: 40, height: 1.2), headlineSmall: base.textTheme.headlineSmall?.copyWith(fontFamily: arabic ? 'Beiruti' : c['displayFamily'] as String, fontSize: 28, height: 1.28), bodyLarge: base.textTheme.bodyLarge?.copyWith(fontSize: arabic ? 18 : 16, height: 1.5)),
    filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(minimumSize: const Size(48, 56), shape: RoundedRectangleBorder(borderRadius: radius))),
    outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(minimumSize: const Size(48, 56), shape: RoundedRectangleBorder(borderRadius: radius))),
    inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: scheme.surfaceContainer, border: OutlineInputBorder(borderRadius: radius)),
  );
}

const _themes = <String, Map<String, Map<String, Object>>>{
  'Clarity': {
    'light': {
      'surface': 0xFFFAF9F5,
      'surfaceContainer': 0xFFFFFFFF,
      'surfaceSoft': 0xFFF0EFE9,
      'onSurface': 0xFF142238,
      'onSurfaceVariant': 0xFF546174,
      'outline': 0xFF77828C,
      'outlineVariant': 0xFFDCDCD6,
      'primary': 0xFF216BED,
      'onPrimary': 0xFFFFFFFF,
      'primaryContainer': 0xFFEAF0FF,
      'onPrimaryContainer': 0xFF07315F,
      'success': 0xFF176541,
      'successContainer': 0xFFE8F5EC,
      'warning': 0xFF805314,
      'warningContainer': 0xFFFFF2D5,
      'error': 0xFFAC292C,
      'errorContainer': 0xFFFDEDEB,
      'focus': 0xFF0067C5,
      'disabled': 0xFFF0EFE9,
      'onDisabled': 0xFF546174,
      'controlRadius': 12.0,
      'displayFamily': 'Hanken Grotesk',
    },
    'dark': {
      'surface': 0xFF111821,
      'surfaceContainer': 0xFF1B2530,
      'surfaceSoft': 0xFF253240,
      'onSurface': 0xFFF3F1EA,
      'onSurfaceVariant': 0xFFBFC9D4,
      'outline': 0xFF596B80,
      'outlineVariant': 0xFF253240,
      'primary': 0xFFA9C8FF,
      'onPrimary': 0xFF07315F,
      'primaryContainer': 0xFF163A76,
      'onPrimaryContainer': 0xFFA9C8FF,
      'success': 0xFF92D7AE,
      'successContainer': 0xFF173B2B,
      'warning': 0xFFEFCC85,
      'warningContainer': 0xFF3E321D,
      'error': 0xFFFFB4AC,
      'errorContainer': 0xFF492729,
      'focus': 0xFF3BC1EE,
      'disabled': 0xFF253240,
      'onDisabled': 0xFFBFC9D4,
      'controlRadius': 12.0,
      'displayFamily': 'Hanken Grotesk',
    },
  },
  'Reserve': {
    'light': {
      'surface': 0xFFFAF9F5,
      'surfaceContainer': 0xFFFFFFFF,
      'surfaceSoft': 0xFFF0EFE9,
      'onSurface': 0xFF142238,
      'onSurfaceVariant': 0xFF546174,
      'outline': 0xFF77828C,
      'outlineVariant': 0xFFDCDCD6,
      'primary': 0xFF114075,
      'onPrimary': 0xFFFFFFFF,
      'primaryContainer': 0xFFEAF2F5,
      'onPrimaryContainer': 0xFF07315F,
      'success': 0xFF176541,
      'successContainer': 0xFFE8F5EC,
      'warning': 0xFF805314,
      'warningContainer': 0xFFFFF2D5,
      'error': 0xFFAC292C,
      'errorContainer': 0xFFFDEDEB,
      'focus': 0xFF0067C5,
      'disabled': 0xFFF0EFE9,
      'onDisabled': 0xFF546174,
      'controlRadius': 8.0,
      'displayFamily': 'Hanken Grotesk',
    },
    'dark': {
      'surface': 0xFF111821,
      'surfaceContainer': 0xFF1B2530,
      'surfaceSoft': 0xFF253240,
      'onSurface': 0xFFF3F1EA,
      'onSurfaceVariant': 0xFFBFC9D4,
      'outline': 0xFF596B80,
      'outlineVariant': 0xFF253240,
      'primary': 0xFFB4CDEA,
      'onPrimary': 0xFF07315F,
      'primaryContainer': 0xFF173957,
      'onPrimaryContainer': 0xFFB4CDEA,
      'success': 0xFF92D7AE,
      'successContainer': 0xFF173B2B,
      'warning': 0xFFEFCC85,
      'warningContainer': 0xFF3E321D,
      'error': 0xFFFFB4AC,
      'errorContainer': 0xFF492729,
      'focus': 0xFF3BC1EE,
      'disabled': 0xFF253240,
      'onDisabled': 0xFFBFC9D4,
      'controlRadius': 8.0,
      'displayFamily': 'Hanken Grotesk',
    },
  },
  'Drive': {
    'light': {
      'surface': 0xFFFAF9F5,
      'surfaceContainer': 0xFFFFFFFF,
      'surfaceSoft': 0xFFF0EFE9,
      'onSurface': 0xFF142238,
      'onSurfaceVariant': 0xFF546174,
      'outline': 0xFF77828C,
      'outlineVariant': 0xFFDCDCD6,
      'primary': 0xFF125545,
      'onPrimary': 0xFFFFFFFF,
      'primaryContainer': 0xFFDCF3DE,
      'onPrimaryContainer': 0xFF07315F,
      'success': 0xFF176541,
      'successContainer': 0xFFE8F5EC,
      'warning': 0xFF805314,
      'warningContainer': 0xFFFFF2D5,
      'error': 0xFFAC292C,
      'errorContainer': 0xFFFDEDEB,
      'focus': 0xFF0067C5,
      'disabled': 0xFFF0EFE9,
      'onDisabled': 0xFF546174,
      'controlRadius': 24.0,
      'displayFamily': 'Baloo 2',
    },
    'dark': {
      'surface': 0xFF111821,
      'surfaceContainer': 0xFF1B2530,
      'surfaceSoft': 0xFF253240,
      'onSurface': 0xFFF3F1EA,
      'onSurfaceVariant': 0xFFBFC9D4,
      'outline': 0xFF596B80,
      'outlineVariant': 0xFF253240,
      'primary': 0xFFA9E0BC,
      'onPrimary': 0xFF07315F,
      'primaryContainer': 0xFF173E32,
      'onPrimaryContainer': 0xFFA9E0BC,
      'success': 0xFF92D7AE,
      'successContainer': 0xFF173B2B,
      'warning': 0xFFEFCC85,
      'warningContainer': 0xFF3E321D,
      'error': 0xFFFFB4AC,
      'errorContainer': 0xFF492729,
      'focus': 0xFF3BC1EE,
      'disabled': 0xFF253240,
      'onDisabled': 0xFFBFC9D4,
      'controlRadius': 24.0,
      'displayFamily': 'Baloo 2',
    },
  },
  'Orbit': {
    'light': {
      'surface': 0xFFFAF9F5,
      'surfaceContainer': 0xFFFFFFFF,
      'surfaceSoft': 0xFFF0EFE9,
      'onSurface': 0xFF142238,
      'onSurfaceVariant': 0xFF546174,
      'outline': 0xFF77828C,
      'outlineVariant': 0xFFDCDCD6,
      'primary': 0xFF07315F,
      'onPrimary': 0xFFFFFFFF,
      'primaryContainer': 0xFFFFF3BB,
      'onPrimaryContainer': 0xFF07315F,
      'success': 0xFF176541,
      'successContainer': 0xFFE8F5EC,
      'warning': 0xFF805314,
      'warningContainer': 0xFFFFF2D5,
      'error': 0xFFAC292C,
      'errorContainer': 0xFFFDEDEB,
      'focus': 0xFF0067C5,
      'disabled': 0xFFF0EFE9,
      'onDisabled': 0xFF546174,
      'controlRadius': 20.0,
      'displayFamily': 'Baloo 2',
    },
    'dark': {
      'surface': 0xFF111821,
      'surfaceContainer': 0xFF1B2530,
      'surfaceSoft': 0xFF253240,
      'onSurface': 0xFFF3F1EA,
      'onSurfaceVariant': 0xFFBFC9D4,
      'outline': 0xFF596B80,
      'outlineVariant': 0xFF253240,
      'primary': 0xFFB9DDF5,
      'onPrimary': 0xFF07315F,
      'primaryContainer': 0xFF283749,
      'onPrimaryContainer': 0xFFB9DDF5,
      'success': 0xFF92D7AE,
      'successContainer': 0xFF173B2B,
      'warning': 0xFFEFCC85,
      'warningContainer': 0xFF3E321D,
      'error': 0xFFFFB4AC,
      'errorContainer': 0xFF492729,
      'focus': 0xFF3BC1EE,
      'disabled': 0xFF253240,
      'onDisabled': 0xFFBFC9D4,
      'controlRadius': 20.0,
      'displayFamily': 'Baloo 2',
    },
  },
};
